/*
OpenAPI

Testing DefaultAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package webrobot

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_webrobot_DefaultAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DefaultAPIService AddJobToProject", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string

		httpRes, err := apiClient.DefaultAPI.AddJobToProject(context.Background(), projectId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService CancelTraining", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var provider string
		var jobId string

		httpRes, err := apiClient.DefaultAPI.CancelTraining(context.Background(), provider, jobId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService CreateAgent", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.DefaultAPI.CreateAgent(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService CreateCategory", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.DefaultAPI.CreateCategory(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService CreateProject", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.DefaultAPI.CreateProject(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService CreateTask", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var jobId string

		httpRes, err := apiClient.DefaultAPI.CreateTask(context.Background(), projectId, jobId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService Delete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var table string
		var id string

		httpRes, err := apiClient.DefaultAPI.Delete(context.Background(), table, id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService DeleteAgent", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agentId string

		httpRes, err := apiClient.DefaultAPI.DeleteAgent(context.Background(), agentId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService DeleteCategory", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var categoryId string

		httpRes, err := apiClient.DefaultAPI.DeleteCategory(context.Background(), categoryId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService DeleteDataset", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var datasetId string

		httpRes, err := apiClient.DefaultAPI.DeleteDataset(context.Background(), datasetId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService DeleteDatasetVersion", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var versionsetId string

		httpRes, err := apiClient.DefaultAPI.DeleteDatasetVersion(context.Background(), versionsetId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService DeleteProject", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string

		httpRes, err := apiClient.DefaultAPI.DeleteProject(context.Background(), projectId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService DeleteTask", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var jobId string
		var taskId string

		httpRes, err := apiClient.DefaultAPI.DeleteTask(context.Background(), projectId, jobId, taskId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService DownloadModel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var provider string
		var jobId string

		httpRes, err := apiClient.DefaultAPI.DownloadModel(context.Background(), provider, jobId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService EstimateCost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var provider string

		httpRes, err := apiClient.DefaultAPI.EstimateCost(context.Background(), provider).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService FindAll", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var table string

		httpRes, err := apiClient.DefaultAPI.FindAll(context.Background(), table).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetAgent", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var categoryId string
		var agentId string

		httpRes, err := apiClient.DefaultAPI.GetAgent(context.Background(), categoryId, agentId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetAgentFromName", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var categoryId string
		var agentName string

		httpRes, err := apiClient.DefaultAPI.GetAgentFromName(context.Background(), categoryId, agentName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetAllAgents", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var categoryId string

		httpRes, err := apiClient.DefaultAPI.GetAllAgents(context.Background(), categoryId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetAllCategories", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.DefaultAPI.GetAllCategories(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetAllDatasetVersions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.DefaultAPI.GetAllDatasetVersions(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetAllDatasets", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.DefaultAPI.GetAllDatasets(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetAllProjects", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.DefaultAPI.GetAllProjects(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetAllTasks", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var jobId string

		httpRes, err := apiClient.DefaultAPI.GetAllTasks(context.Background(), projectId, jobId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetAllVersionsets", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var datasetId string

		httpRes, err := apiClient.DefaultAPI.GetAllVersionsets(context.Background(), datasetId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var table string
		var id string

		httpRes, err := apiClient.DefaultAPI.GetById(context.Background(), table, id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetCategory", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var categoryId string

		httpRes, err := apiClient.DefaultAPI.GetCategory(context.Background(), categoryId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetCategoryFromName", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var categoryName string

		httpRes, err := apiClient.DefaultAPI.GetCategoryFromName(context.Background(), categoryName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetDataset", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var datasetId string

		httpRes, err := apiClient.DefaultAPI.GetDataset(context.Background(), datasetId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetDatasetInputFile", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var datasetId string

		httpRes, err := apiClient.DefaultAPI.GetDatasetInputFile(context.Background(), datasetId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetDatasetInputFilePagination", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var offset int32
		var datasetId string
		var limit int32

		httpRes, err := apiClient.DefaultAPI.GetDatasetInputFilePagination(context.Background(), offset, datasetId, limit).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetDatasetInputFileSize", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var datasetId string

		httpRes, err := apiClient.DefaultAPI.GetDatasetInputFileSize(context.Background(), datasetId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetDatasetStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var datasetId string

		httpRes, err := apiClient.DefaultAPI.GetDatasetStatus(context.Background(), datasetId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetDatasetVersionInputFile", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var categoryId string
		var jobId string
		var versionsetId string
		var datasetId string

		httpRes, err := apiClient.DefaultAPI.GetDatasetVersionInputFile(context.Background(), categoryId, jobId, versionsetId, datasetId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetDatasetVersionInputFilePagination", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var botId string
		var offset int32
		var limit int32
		var versionsetId string
		var datasetId string

		httpRes, err := apiClient.DefaultAPI.GetDatasetVersionInputFilePagination(context.Background(), projectId, botId, offset, limit, versionsetId, datasetId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetHealth", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.DefaultAPI.GetHealth(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetHtml", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var protocol string
		var url string

		httpRes, err := apiClient.DefaultAPI.GetHtml(context.Background(), protocol, url).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetProject", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string

		httpRes, err := apiClient.DefaultAPI.GetProject(context.Background(), projectId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetProjectFromName", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectName string

		httpRes, err := apiClient.DefaultAPI.GetProjectFromName(context.Background(), projectName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetProjectJobs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string

		httpRes, err := apiClient.DefaultAPI.GetProjectJobs(context.Background(), projectId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetProjectSchedule", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string

		httpRes, err := apiClient.DefaultAPI.GetProjectSchedule(context.Background(), projectId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetSupportedModels", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var provider string

		httpRes, err := apiClient.DefaultAPI.GetSupportedModels(context.Background(), provider).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetSupportedProviders", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.DefaultAPI.GetSupportedProviders(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetTask", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var jobId string
		var taskId string

		httpRes, err := apiClient.DefaultAPI.GetTask(context.Background(), projectId, jobId, taskId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetTaskStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var jobId string
		var taskId string

		httpRes, err := apiClient.DefaultAPI.GetTaskStatus(context.Background(), projectId, jobId, taskId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetTrainingLogs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var provider string
		var jobId string

		httpRes, err := apiClient.DefaultAPI.GetTrainingLogs(context.Background(), provider, jobId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetTrainingStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var provider string
		var jobId string

		httpRes, err := apiClient.DefaultAPI.GetTrainingStatus(context.Background(), provider, jobId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetUploadFileUrl", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var botId string
		var attachmentName string

		httpRes, err := apiClient.DefaultAPI.GetUploadFileUrl(context.Background(), projectId, botId, attachmentName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetUrlDownload", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.DefaultAPI.GetUrlDownload(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetUrlUpload", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.DefaultAPI.GetUrlUpload(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetVersionset", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var versionsetId string

		httpRes, err := apiClient.DefaultAPI.GetVersionset(context.Background(), versionsetId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetVersionsetFromVersion", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var datasetId string
		var version string

		httpRes, err := apiClient.DefaultAPI.GetVersionsetFromVersion(context.Background(), datasetId, version).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetVersionsetFromVersionBase", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var datasetId string
		var version string

		httpRes, err := apiClient.DefaultAPI.GetVersionsetFromVersionBase(context.Background(), datasetId, version).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService Insert", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var table string

		httpRes, err := apiClient.DefaultAPI.Insert(context.Background(), table).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService PublishModel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.DefaultAPI.PublishModel(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService RemoveJobFromProject", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var jobId string

		httpRes, err := apiClient.DefaultAPI.RemoveJobFromProject(context.Background(), projectId, jobId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService SetProjectSchedule", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string

		httpRes, err := apiClient.DefaultAPI.SetProjectSchedule(context.Background(), projectId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService StartExportAll", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.DefaultAPI.StartExportAll(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService StartExportProject", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string

		httpRes, err := apiClient.DefaultAPI.StartExportProject(context.Background(), projectId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService StartImportAll", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.DefaultAPI.StartImportAll(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService StartImportProject", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string

		httpRes, err := apiClient.DefaultAPI.StartImportProject(context.Background(), projectId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService StartTask", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var jobId string
		var taskId string

		httpRes, err := apiClient.DefaultAPI.StartTask(context.Background(), projectId, jobId, taskId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService StartTraining", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var provider string

		httpRes, err := apiClient.DefaultAPI.StartTraining(context.Background(), provider).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService StopTask", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var jobId string
		var taskId string

		httpRes, err := apiClient.DefaultAPI.StopTask(context.Background(), projectId, jobId, taskId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService Test", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.DefaultAPI.Test(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService Test1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.DefaultAPI.Test1(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService Update", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var table string
		var id string

		httpRes, err := apiClient.DefaultAPI.Update(context.Background(), table, id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService UpdateAgent", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var categoryId string
		var agentId string

		httpRes, err := apiClient.DefaultAPI.UpdateAgent(context.Background(), categoryId, agentId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService UpdateCategory", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var categoryId string

		httpRes, err := apiClient.DefaultAPI.UpdateCategory(context.Background(), categoryId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService UpdateProject", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string

		httpRes, err := apiClient.DefaultAPI.UpdateProject(context.Background(), projectId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService UpdateTask", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var jobId string
		var taskId string

		httpRes, err := apiClient.DefaultAPI.UpdateTask(context.Background(), projectId, jobId, taskId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService UploadDataset", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var provider string

		httpRes, err := apiClient.DefaultAPI.UploadDataset(context.Background(), provider).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService UploadDataset1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.DefaultAPI.UploadDataset1(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
