/*
OpenAPI

OpenAPI

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package webrobot

import (
	"encoding/json"
)

// checks if the StartRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StartRequest{}

// StartRequest struct for StartRequest
type StartRequest struct {
	ProfileId *int32 `json:"profileId,omitempty"`
	ProfileName *string `json:"profileName,omitempty"`
	ProfileUrl *string `json:"profileUrl,omitempty"`
	Inputs *map[string]string `json:"inputs,omitempty"`
	LlmProvider *string `json:"llmProvider,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
	ClusterSelector *string `json:"clusterSelector,omitempty"`
	Image *string `json:"image,omitempty"`
	WorkingDir *string `json:"workingDir,omitempty"`
	Entrypoint *string `json:"entrypoint,omitempty"`
	RuntimeEnvYaml *string `json:"runtimeEnvYaml,omitempty"`
	TtlSeconds *int32 `json:"ttlSeconds,omitempty"`
	ActiveDeadlineSeconds *int32 `json:"activeDeadlineSeconds,omitempty"`
	EnvPassthrough *map[string]string `json:"envPassthrough,omitempty"`
	OrganizationId *string `json:"organizationId,omitempty"`
	ProjectId *string `json:"projectId,omitempty"`
	UserId *string `json:"userId,omitempty"`
}

// NewStartRequest instantiates a new StartRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStartRequest() *StartRequest {
	this := StartRequest{}
	return &this
}

// NewStartRequestWithDefaults instantiates a new StartRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStartRequestWithDefaults() *StartRequest {
	this := StartRequest{}
	return &this
}

// GetProfileId returns the ProfileId field value if set, zero value otherwise.
func (o *StartRequest) GetProfileId() int32 {
	if o == nil || IsNil(o.ProfileId) {
		var ret int32
		return ret
	}
	return *o.ProfileId
}

// GetProfileIdOk returns a tuple with the ProfileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartRequest) GetProfileIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ProfileId) {
		return nil, false
	}
	return o.ProfileId, true
}

// HasProfileId returns a boolean if a field has been set.
func (o *StartRequest) HasProfileId() bool {
	if o != nil && !IsNil(o.ProfileId) {
		return true
	}

	return false
}

// SetProfileId gets a reference to the given int32 and assigns it to the ProfileId field.
func (o *StartRequest) SetProfileId(v int32) {
	o.ProfileId = &v
}

// GetProfileName returns the ProfileName field value if set, zero value otherwise.
func (o *StartRequest) GetProfileName() string {
	if o == nil || IsNil(o.ProfileName) {
		var ret string
		return ret
	}
	return *o.ProfileName
}

// GetProfileNameOk returns a tuple with the ProfileName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartRequest) GetProfileNameOk() (*string, bool) {
	if o == nil || IsNil(o.ProfileName) {
		return nil, false
	}
	return o.ProfileName, true
}

// HasProfileName returns a boolean if a field has been set.
func (o *StartRequest) HasProfileName() bool {
	if o != nil && !IsNil(o.ProfileName) {
		return true
	}

	return false
}

// SetProfileName gets a reference to the given string and assigns it to the ProfileName field.
func (o *StartRequest) SetProfileName(v string) {
	o.ProfileName = &v
}

// GetProfileUrl returns the ProfileUrl field value if set, zero value otherwise.
func (o *StartRequest) GetProfileUrl() string {
	if o == nil || IsNil(o.ProfileUrl) {
		var ret string
		return ret
	}
	return *o.ProfileUrl
}

// GetProfileUrlOk returns a tuple with the ProfileUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartRequest) GetProfileUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ProfileUrl) {
		return nil, false
	}
	return o.ProfileUrl, true
}

// HasProfileUrl returns a boolean if a field has been set.
func (o *StartRequest) HasProfileUrl() bool {
	if o != nil && !IsNil(o.ProfileUrl) {
		return true
	}

	return false
}

// SetProfileUrl gets a reference to the given string and assigns it to the ProfileUrl field.
func (o *StartRequest) SetProfileUrl(v string) {
	o.ProfileUrl = &v
}

// GetInputs returns the Inputs field value if set, zero value otherwise.
func (o *StartRequest) GetInputs() map[string]string {
	if o == nil || IsNil(o.Inputs) {
		var ret map[string]string
		return ret
	}
	return *o.Inputs
}

// GetInputsOk returns a tuple with the Inputs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartRequest) GetInputsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Inputs) {
		return nil, false
	}
	return o.Inputs, true
}

// HasInputs returns a boolean if a field has been set.
func (o *StartRequest) HasInputs() bool {
	if o != nil && !IsNil(o.Inputs) {
		return true
	}

	return false
}

// SetInputs gets a reference to the given map[string]string and assigns it to the Inputs field.
func (o *StartRequest) SetInputs(v map[string]string) {
	o.Inputs = &v
}

// GetLlmProvider returns the LlmProvider field value if set, zero value otherwise.
func (o *StartRequest) GetLlmProvider() string {
	if o == nil || IsNil(o.LlmProvider) {
		var ret string
		return ret
	}
	return *o.LlmProvider
}

// GetLlmProviderOk returns a tuple with the LlmProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartRequest) GetLlmProviderOk() (*string, bool) {
	if o == nil || IsNil(o.LlmProvider) {
		return nil, false
	}
	return o.LlmProvider, true
}

// HasLlmProvider returns a boolean if a field has been set.
func (o *StartRequest) HasLlmProvider() bool {
	if o != nil && !IsNil(o.LlmProvider) {
		return true
	}

	return false
}

// SetLlmProvider gets a reference to the given string and assigns it to the LlmProvider field.
func (o *StartRequest) SetLlmProvider(v string) {
	o.LlmProvider = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *StartRequest) GetNamespace() string {
	if o == nil || IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartRequest) GetNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *StartRequest) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *StartRequest) SetNamespace(v string) {
	o.Namespace = &v
}

// GetClusterSelector returns the ClusterSelector field value if set, zero value otherwise.
func (o *StartRequest) GetClusterSelector() string {
	if o == nil || IsNil(o.ClusterSelector) {
		var ret string
		return ret
	}
	return *o.ClusterSelector
}

// GetClusterSelectorOk returns a tuple with the ClusterSelector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartRequest) GetClusterSelectorOk() (*string, bool) {
	if o == nil || IsNil(o.ClusterSelector) {
		return nil, false
	}
	return o.ClusterSelector, true
}

// HasClusterSelector returns a boolean if a field has been set.
func (o *StartRequest) HasClusterSelector() bool {
	if o != nil && !IsNil(o.ClusterSelector) {
		return true
	}

	return false
}

// SetClusterSelector gets a reference to the given string and assigns it to the ClusterSelector field.
func (o *StartRequest) SetClusterSelector(v string) {
	o.ClusterSelector = &v
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *StartRequest) GetImage() string {
	if o == nil || IsNil(o.Image) {
		var ret string
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartRequest) GetImageOk() (*string, bool) {
	if o == nil || IsNil(o.Image) {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *StartRequest) HasImage() bool {
	if o != nil && !IsNil(o.Image) {
		return true
	}

	return false
}

// SetImage gets a reference to the given string and assigns it to the Image field.
func (o *StartRequest) SetImage(v string) {
	o.Image = &v
}

// GetWorkingDir returns the WorkingDir field value if set, zero value otherwise.
func (o *StartRequest) GetWorkingDir() string {
	if o == nil || IsNil(o.WorkingDir) {
		var ret string
		return ret
	}
	return *o.WorkingDir
}

// GetWorkingDirOk returns a tuple with the WorkingDir field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartRequest) GetWorkingDirOk() (*string, bool) {
	if o == nil || IsNil(o.WorkingDir) {
		return nil, false
	}
	return o.WorkingDir, true
}

// HasWorkingDir returns a boolean if a field has been set.
func (o *StartRequest) HasWorkingDir() bool {
	if o != nil && !IsNil(o.WorkingDir) {
		return true
	}

	return false
}

// SetWorkingDir gets a reference to the given string and assigns it to the WorkingDir field.
func (o *StartRequest) SetWorkingDir(v string) {
	o.WorkingDir = &v
}

// GetEntrypoint returns the Entrypoint field value if set, zero value otherwise.
func (o *StartRequest) GetEntrypoint() string {
	if o == nil || IsNil(o.Entrypoint) {
		var ret string
		return ret
	}
	return *o.Entrypoint
}

// GetEntrypointOk returns a tuple with the Entrypoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartRequest) GetEntrypointOk() (*string, bool) {
	if o == nil || IsNil(o.Entrypoint) {
		return nil, false
	}
	return o.Entrypoint, true
}

// HasEntrypoint returns a boolean if a field has been set.
func (o *StartRequest) HasEntrypoint() bool {
	if o != nil && !IsNil(o.Entrypoint) {
		return true
	}

	return false
}

// SetEntrypoint gets a reference to the given string and assigns it to the Entrypoint field.
func (o *StartRequest) SetEntrypoint(v string) {
	o.Entrypoint = &v
}

// GetRuntimeEnvYaml returns the RuntimeEnvYaml field value if set, zero value otherwise.
func (o *StartRequest) GetRuntimeEnvYaml() string {
	if o == nil || IsNil(o.RuntimeEnvYaml) {
		var ret string
		return ret
	}
	return *o.RuntimeEnvYaml
}

// GetRuntimeEnvYamlOk returns a tuple with the RuntimeEnvYaml field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartRequest) GetRuntimeEnvYamlOk() (*string, bool) {
	if o == nil || IsNil(o.RuntimeEnvYaml) {
		return nil, false
	}
	return o.RuntimeEnvYaml, true
}

// HasRuntimeEnvYaml returns a boolean if a field has been set.
func (o *StartRequest) HasRuntimeEnvYaml() bool {
	if o != nil && !IsNil(o.RuntimeEnvYaml) {
		return true
	}

	return false
}

// SetRuntimeEnvYaml gets a reference to the given string and assigns it to the RuntimeEnvYaml field.
func (o *StartRequest) SetRuntimeEnvYaml(v string) {
	o.RuntimeEnvYaml = &v
}

// GetTtlSeconds returns the TtlSeconds field value if set, zero value otherwise.
func (o *StartRequest) GetTtlSeconds() int32 {
	if o == nil || IsNil(o.TtlSeconds) {
		var ret int32
		return ret
	}
	return *o.TtlSeconds
}

// GetTtlSecondsOk returns a tuple with the TtlSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartRequest) GetTtlSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.TtlSeconds) {
		return nil, false
	}
	return o.TtlSeconds, true
}

// HasTtlSeconds returns a boolean if a field has been set.
func (o *StartRequest) HasTtlSeconds() bool {
	if o != nil && !IsNil(o.TtlSeconds) {
		return true
	}

	return false
}

// SetTtlSeconds gets a reference to the given int32 and assigns it to the TtlSeconds field.
func (o *StartRequest) SetTtlSeconds(v int32) {
	o.TtlSeconds = &v
}

// GetActiveDeadlineSeconds returns the ActiveDeadlineSeconds field value if set, zero value otherwise.
func (o *StartRequest) GetActiveDeadlineSeconds() int32 {
	if o == nil || IsNil(o.ActiveDeadlineSeconds) {
		var ret int32
		return ret
	}
	return *o.ActiveDeadlineSeconds
}

// GetActiveDeadlineSecondsOk returns a tuple with the ActiveDeadlineSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartRequest) GetActiveDeadlineSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.ActiveDeadlineSeconds) {
		return nil, false
	}
	return o.ActiveDeadlineSeconds, true
}

// HasActiveDeadlineSeconds returns a boolean if a field has been set.
func (o *StartRequest) HasActiveDeadlineSeconds() bool {
	if o != nil && !IsNil(o.ActiveDeadlineSeconds) {
		return true
	}

	return false
}

// SetActiveDeadlineSeconds gets a reference to the given int32 and assigns it to the ActiveDeadlineSeconds field.
func (o *StartRequest) SetActiveDeadlineSeconds(v int32) {
	o.ActiveDeadlineSeconds = &v
}

// GetEnvPassthrough returns the EnvPassthrough field value if set, zero value otherwise.
func (o *StartRequest) GetEnvPassthrough() map[string]string {
	if o == nil || IsNil(o.EnvPassthrough) {
		var ret map[string]string
		return ret
	}
	return *o.EnvPassthrough
}

// GetEnvPassthroughOk returns a tuple with the EnvPassthrough field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartRequest) GetEnvPassthroughOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.EnvPassthrough) {
		return nil, false
	}
	return o.EnvPassthrough, true
}

// HasEnvPassthrough returns a boolean if a field has been set.
func (o *StartRequest) HasEnvPassthrough() bool {
	if o != nil && !IsNil(o.EnvPassthrough) {
		return true
	}

	return false
}

// SetEnvPassthrough gets a reference to the given map[string]string and assigns it to the EnvPassthrough field.
func (o *StartRequest) SetEnvPassthrough(v map[string]string) {
	o.EnvPassthrough = &v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *StartRequest) GetOrganizationId() string {
	if o == nil || IsNil(o.OrganizationId) {
		var ret string
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartRequest) GetOrganizationIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *StartRequest) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given string and assigns it to the OrganizationId field.
func (o *StartRequest) SetOrganizationId(v string) {
	o.OrganizationId = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *StartRequest) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartRequest) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *StartRequest) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *StartRequest) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *StartRequest) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartRequest) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *StartRequest) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *StartRequest) SetUserId(v string) {
	o.UserId = &v
}

func (o StartRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StartRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProfileId) {
		toSerialize["profileId"] = o.ProfileId
	}
	if !IsNil(o.ProfileName) {
		toSerialize["profileName"] = o.ProfileName
	}
	if !IsNil(o.ProfileUrl) {
		toSerialize["profileUrl"] = o.ProfileUrl
	}
	if !IsNil(o.Inputs) {
		toSerialize["inputs"] = o.Inputs
	}
	if !IsNil(o.LlmProvider) {
		toSerialize["llmProvider"] = o.LlmProvider
	}
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	if !IsNil(o.ClusterSelector) {
		toSerialize["clusterSelector"] = o.ClusterSelector
	}
	if !IsNil(o.Image) {
		toSerialize["image"] = o.Image
	}
	if !IsNil(o.WorkingDir) {
		toSerialize["workingDir"] = o.WorkingDir
	}
	if !IsNil(o.Entrypoint) {
		toSerialize["entrypoint"] = o.Entrypoint
	}
	if !IsNil(o.RuntimeEnvYaml) {
		toSerialize["runtimeEnvYaml"] = o.RuntimeEnvYaml
	}
	if !IsNil(o.TtlSeconds) {
		toSerialize["ttlSeconds"] = o.TtlSeconds
	}
	if !IsNil(o.ActiveDeadlineSeconds) {
		toSerialize["activeDeadlineSeconds"] = o.ActiveDeadlineSeconds
	}
	if !IsNil(o.EnvPassthrough) {
		toSerialize["envPassthrough"] = o.EnvPassthrough
	}
	if !IsNil(o.OrganizationId) {
		toSerialize["organizationId"] = o.OrganizationId
	}
	if !IsNil(o.ProjectId) {
		toSerialize["projectId"] = o.ProjectId
	}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}
	return toSerialize, nil
}

type NullableStartRequest struct {
	value *StartRequest
	isSet bool
}

func (v NullableStartRequest) Get() *StartRequest {
	return v.value
}

func (v *NullableStartRequest) Set(val *StartRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableStartRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableStartRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStartRequest(val *StartRequest) *NullableStartRequest {
	return &NullableStartRequest{value: val, isSet: true}
}

func (v NullableStartRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStartRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


