/*
OpenAPI

OpenAPI

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package webrobot

import (
	"encoding/json"
)

// checks if the CompletionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompletionRequest{}

// CompletionRequest struct for CompletionRequest
type CompletionRequest struct {
	Status *string `json:"status,omitempty"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
	Result map[string]map[string]interface{} `json:"result,omitempty"`
	Tokens map[string]map[string]interface{} `json:"tokens,omitempty"`
}

// NewCompletionRequest instantiates a new CompletionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompletionRequest() *CompletionRequest {
	this := CompletionRequest{}
	return &this
}

// NewCompletionRequestWithDefaults instantiates a new CompletionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompletionRequestWithDefaults() *CompletionRequest {
	this := CompletionRequest{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CompletionRequest) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompletionRequest) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CompletionRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CompletionRequest) SetStatus(v string) {
	o.Status = &v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *CompletionRequest) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompletionRequest) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *CompletionRequest) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *CompletionRequest) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *CompletionRequest) GetResult() map[string]map[string]interface{} {
	if o == nil || IsNil(o.Result) {
		var ret map[string]map[string]interface{}
		return ret
	}
	return o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompletionRequest) GetResultOk() (map[string]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Result) {
		return map[string]map[string]interface{}{}, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *CompletionRequest) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given map[string]map[string]interface{} and assigns it to the Result field.
func (o *CompletionRequest) SetResult(v map[string]map[string]interface{}) {
	o.Result = v
}

// GetTokens returns the Tokens field value if set, zero value otherwise.
func (o *CompletionRequest) GetTokens() map[string]map[string]interface{} {
	if o == nil || IsNil(o.Tokens) {
		var ret map[string]map[string]interface{}
		return ret
	}
	return o.Tokens
}

// GetTokensOk returns a tuple with the Tokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompletionRequest) GetTokensOk() (map[string]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Tokens) {
		return map[string]map[string]interface{}{}, false
	}
	return o.Tokens, true
}

// HasTokens returns a boolean if a field has been set.
func (o *CompletionRequest) HasTokens() bool {
	if o != nil && !IsNil(o.Tokens) {
		return true
	}

	return false
}

// SetTokens gets a reference to the given map[string]map[string]interface{} and assigns it to the Tokens field.
func (o *CompletionRequest) SetTokens(v map[string]map[string]interface{}) {
	o.Tokens = v
}

func (o CompletionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompletionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.ErrorMessage) {
		toSerialize["errorMessage"] = o.ErrorMessage
	}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Tokens) {
		toSerialize["tokens"] = o.Tokens
	}
	return toSerialize, nil
}

type NullableCompletionRequest struct {
	value *CompletionRequest
	isSet bool
}

func (v NullableCompletionRequest) Get() *CompletionRequest {
	return v.value
}

func (v *NullableCompletionRequest) Set(val *CompletionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCompletionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCompletionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompletionRequest(val *CompletionRequest) *NullableCompletionRequest {
	return &NullableCompletionRequest{value: val, isSet: true}
}

func (v NullableCompletionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompletionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


