/*
OpenAPI

OpenAPI

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package webrobot

import (
	"encoding/json"
	"time"
)

// checks if the EtlLibraryVersionApiDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EtlLibraryVersionApiDto{}

// EtlLibraryVersionApiDto struct for EtlLibraryVersionApiDto
type EtlLibraryVersionApiDto struct {
	Id *int64 `json:"id,omitempty"`
	BuildType *string `json:"buildType,omitempty"`
	BuildNumber *int32 `json:"buildNumber,omitempty"`
	Version *string `json:"version,omitempty"`
	JarPath *string `json:"jarPath,omitempty"`
	JarPathObfuscated *string `json:"jarPathObfuscated,omitempty"`
	JarSizeBytes *int64 `json:"jarSizeBytes,omitempty"`
	UploadedAt *time.Time `json:"uploadedAt,omitempty"`
	Active *bool `json:"active,omitempty"`
	Description *string `json:"description,omitempty"`
	ImageTag *string `json:"imageTag,omitempty"`
}

// NewEtlLibraryVersionApiDto instantiates a new EtlLibraryVersionApiDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEtlLibraryVersionApiDto() *EtlLibraryVersionApiDto {
	this := EtlLibraryVersionApiDto{}
	return &this
}

// NewEtlLibraryVersionApiDtoWithDefaults instantiates a new EtlLibraryVersionApiDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEtlLibraryVersionApiDtoWithDefaults() *EtlLibraryVersionApiDto {
	this := EtlLibraryVersionApiDto{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EtlLibraryVersionApiDto) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EtlLibraryVersionApiDto) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EtlLibraryVersionApiDto) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *EtlLibraryVersionApiDto) SetId(v int64) {
	o.Id = &v
}

// GetBuildType returns the BuildType field value if set, zero value otherwise.
func (o *EtlLibraryVersionApiDto) GetBuildType() string {
	if o == nil || IsNil(o.BuildType) {
		var ret string
		return ret
	}
	return *o.BuildType
}

// GetBuildTypeOk returns a tuple with the BuildType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EtlLibraryVersionApiDto) GetBuildTypeOk() (*string, bool) {
	if o == nil || IsNil(o.BuildType) {
		return nil, false
	}
	return o.BuildType, true
}

// HasBuildType returns a boolean if a field has been set.
func (o *EtlLibraryVersionApiDto) HasBuildType() bool {
	if o != nil && !IsNil(o.BuildType) {
		return true
	}

	return false
}

// SetBuildType gets a reference to the given string and assigns it to the BuildType field.
func (o *EtlLibraryVersionApiDto) SetBuildType(v string) {
	o.BuildType = &v
}

// GetBuildNumber returns the BuildNumber field value if set, zero value otherwise.
func (o *EtlLibraryVersionApiDto) GetBuildNumber() int32 {
	if o == nil || IsNil(o.BuildNumber) {
		var ret int32
		return ret
	}
	return *o.BuildNumber
}

// GetBuildNumberOk returns a tuple with the BuildNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EtlLibraryVersionApiDto) GetBuildNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.BuildNumber) {
		return nil, false
	}
	return o.BuildNumber, true
}

// HasBuildNumber returns a boolean if a field has been set.
func (o *EtlLibraryVersionApiDto) HasBuildNumber() bool {
	if o != nil && !IsNil(o.BuildNumber) {
		return true
	}

	return false
}

// SetBuildNumber gets a reference to the given int32 and assigns it to the BuildNumber field.
func (o *EtlLibraryVersionApiDto) SetBuildNumber(v int32) {
	o.BuildNumber = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *EtlLibraryVersionApiDto) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EtlLibraryVersionApiDto) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *EtlLibraryVersionApiDto) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *EtlLibraryVersionApiDto) SetVersion(v string) {
	o.Version = &v
}

// GetJarPath returns the JarPath field value if set, zero value otherwise.
func (o *EtlLibraryVersionApiDto) GetJarPath() string {
	if o == nil || IsNil(o.JarPath) {
		var ret string
		return ret
	}
	return *o.JarPath
}

// GetJarPathOk returns a tuple with the JarPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EtlLibraryVersionApiDto) GetJarPathOk() (*string, bool) {
	if o == nil || IsNil(o.JarPath) {
		return nil, false
	}
	return o.JarPath, true
}

// HasJarPath returns a boolean if a field has been set.
func (o *EtlLibraryVersionApiDto) HasJarPath() bool {
	if o != nil && !IsNil(o.JarPath) {
		return true
	}

	return false
}

// SetJarPath gets a reference to the given string and assigns it to the JarPath field.
func (o *EtlLibraryVersionApiDto) SetJarPath(v string) {
	o.JarPath = &v
}

// GetJarPathObfuscated returns the JarPathObfuscated field value if set, zero value otherwise.
func (o *EtlLibraryVersionApiDto) GetJarPathObfuscated() string {
	if o == nil || IsNil(o.JarPathObfuscated) {
		var ret string
		return ret
	}
	return *o.JarPathObfuscated
}

// GetJarPathObfuscatedOk returns a tuple with the JarPathObfuscated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EtlLibraryVersionApiDto) GetJarPathObfuscatedOk() (*string, bool) {
	if o == nil || IsNil(o.JarPathObfuscated) {
		return nil, false
	}
	return o.JarPathObfuscated, true
}

// HasJarPathObfuscated returns a boolean if a field has been set.
func (o *EtlLibraryVersionApiDto) HasJarPathObfuscated() bool {
	if o != nil && !IsNil(o.JarPathObfuscated) {
		return true
	}

	return false
}

// SetJarPathObfuscated gets a reference to the given string and assigns it to the JarPathObfuscated field.
func (o *EtlLibraryVersionApiDto) SetJarPathObfuscated(v string) {
	o.JarPathObfuscated = &v
}

// GetJarSizeBytes returns the JarSizeBytes field value if set, zero value otherwise.
func (o *EtlLibraryVersionApiDto) GetJarSizeBytes() int64 {
	if o == nil || IsNil(o.JarSizeBytes) {
		var ret int64
		return ret
	}
	return *o.JarSizeBytes
}

// GetJarSizeBytesOk returns a tuple with the JarSizeBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EtlLibraryVersionApiDto) GetJarSizeBytesOk() (*int64, bool) {
	if o == nil || IsNil(o.JarSizeBytes) {
		return nil, false
	}
	return o.JarSizeBytes, true
}

// HasJarSizeBytes returns a boolean if a field has been set.
func (o *EtlLibraryVersionApiDto) HasJarSizeBytes() bool {
	if o != nil && !IsNil(o.JarSizeBytes) {
		return true
	}

	return false
}

// SetJarSizeBytes gets a reference to the given int64 and assigns it to the JarSizeBytes field.
func (o *EtlLibraryVersionApiDto) SetJarSizeBytes(v int64) {
	o.JarSizeBytes = &v
}

// GetUploadedAt returns the UploadedAt field value if set, zero value otherwise.
func (o *EtlLibraryVersionApiDto) GetUploadedAt() time.Time {
	if o == nil || IsNil(o.UploadedAt) {
		var ret time.Time
		return ret
	}
	return *o.UploadedAt
}

// GetUploadedAtOk returns a tuple with the UploadedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EtlLibraryVersionApiDto) GetUploadedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UploadedAt) {
		return nil, false
	}
	return o.UploadedAt, true
}

// HasUploadedAt returns a boolean if a field has been set.
func (o *EtlLibraryVersionApiDto) HasUploadedAt() bool {
	if o != nil && !IsNil(o.UploadedAt) {
		return true
	}

	return false
}

// SetUploadedAt gets a reference to the given time.Time and assigns it to the UploadedAt field.
func (o *EtlLibraryVersionApiDto) SetUploadedAt(v time.Time) {
	o.UploadedAt = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *EtlLibraryVersionApiDto) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EtlLibraryVersionApiDto) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *EtlLibraryVersionApiDto) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *EtlLibraryVersionApiDto) SetActive(v bool) {
	o.Active = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *EtlLibraryVersionApiDto) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EtlLibraryVersionApiDto) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *EtlLibraryVersionApiDto) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *EtlLibraryVersionApiDto) SetDescription(v string) {
	o.Description = &v
}

// GetImageTag returns the ImageTag field value if set, zero value otherwise.
func (o *EtlLibraryVersionApiDto) GetImageTag() string {
	if o == nil || IsNil(o.ImageTag) {
		var ret string
		return ret
	}
	return *o.ImageTag
}

// GetImageTagOk returns a tuple with the ImageTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EtlLibraryVersionApiDto) GetImageTagOk() (*string, bool) {
	if o == nil || IsNil(o.ImageTag) {
		return nil, false
	}
	return o.ImageTag, true
}

// HasImageTag returns a boolean if a field has been set.
func (o *EtlLibraryVersionApiDto) HasImageTag() bool {
	if o != nil && !IsNil(o.ImageTag) {
		return true
	}

	return false
}

// SetImageTag gets a reference to the given string and assigns it to the ImageTag field.
func (o *EtlLibraryVersionApiDto) SetImageTag(v string) {
	o.ImageTag = &v
}

func (o EtlLibraryVersionApiDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EtlLibraryVersionApiDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.BuildType) {
		toSerialize["buildType"] = o.BuildType
	}
	if !IsNil(o.BuildNumber) {
		toSerialize["buildNumber"] = o.BuildNumber
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.JarPath) {
		toSerialize["jarPath"] = o.JarPath
	}
	if !IsNil(o.JarPathObfuscated) {
		toSerialize["jarPathObfuscated"] = o.JarPathObfuscated
	}
	if !IsNil(o.JarSizeBytes) {
		toSerialize["jarSizeBytes"] = o.JarSizeBytes
	}
	if !IsNil(o.UploadedAt) {
		toSerialize["uploadedAt"] = o.UploadedAt
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ImageTag) {
		toSerialize["imageTag"] = o.ImageTag
	}
	return toSerialize, nil
}

type NullableEtlLibraryVersionApiDto struct {
	value *EtlLibraryVersionApiDto
	isSet bool
}

func (v NullableEtlLibraryVersionApiDto) Get() *EtlLibraryVersionApiDto {
	return v.value
}

func (v *NullableEtlLibraryVersionApiDto) Set(val *EtlLibraryVersionApiDto) {
	v.value = val
	v.isSet = true
}

func (v NullableEtlLibraryVersionApiDto) IsSet() bool {
	return v.isSet
}

func (v *NullableEtlLibraryVersionApiDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEtlLibraryVersionApiDto(val *EtlLibraryVersionApiDto) *NullableEtlLibraryVersionApiDto {
	return &NullableEtlLibraryVersionApiDto{value: val, isSet: true}
}

func (v NullableEtlLibraryVersionApiDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEtlLibraryVersionApiDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


