/*
OpenAPI

OpenAPI

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package webrobot

import (
	"encoding/json"
)

// checks if the PrestoQueryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrestoQueryRequest{}

// PrestoQueryRequest struct for PrestoQueryRequest
type PrestoQueryRequest struct {
	Sql *string `json:"sql,omitempty"`
	Catalog *string `json:"catalog,omitempty"`
	Schema *string `json:"schema,omitempty"`
	Limit *int32 `json:"limit,omitempty"`
	Offset *int32 `json:"offset,omitempty"`
}

// NewPrestoQueryRequest instantiates a new PrestoQueryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrestoQueryRequest() *PrestoQueryRequest {
	this := PrestoQueryRequest{}
	return &this
}

// NewPrestoQueryRequestWithDefaults instantiates a new PrestoQueryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrestoQueryRequestWithDefaults() *PrestoQueryRequest {
	this := PrestoQueryRequest{}
	return &this
}

// GetSql returns the Sql field value if set, zero value otherwise.
func (o *PrestoQueryRequest) GetSql() string {
	if o == nil || IsNil(o.Sql) {
		var ret string
		return ret
	}
	return *o.Sql
}

// GetSqlOk returns a tuple with the Sql field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrestoQueryRequest) GetSqlOk() (*string, bool) {
	if o == nil || IsNil(o.Sql) {
		return nil, false
	}
	return o.Sql, true
}

// HasSql returns a boolean if a field has been set.
func (o *PrestoQueryRequest) HasSql() bool {
	if o != nil && !IsNil(o.Sql) {
		return true
	}

	return false
}

// SetSql gets a reference to the given string and assigns it to the Sql field.
func (o *PrestoQueryRequest) SetSql(v string) {
	o.Sql = &v
}

// GetCatalog returns the Catalog field value if set, zero value otherwise.
func (o *PrestoQueryRequest) GetCatalog() string {
	if o == nil || IsNil(o.Catalog) {
		var ret string
		return ret
	}
	return *o.Catalog
}

// GetCatalogOk returns a tuple with the Catalog field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrestoQueryRequest) GetCatalogOk() (*string, bool) {
	if o == nil || IsNil(o.Catalog) {
		return nil, false
	}
	return o.Catalog, true
}

// HasCatalog returns a boolean if a field has been set.
func (o *PrestoQueryRequest) HasCatalog() bool {
	if o != nil && !IsNil(o.Catalog) {
		return true
	}

	return false
}

// SetCatalog gets a reference to the given string and assigns it to the Catalog field.
func (o *PrestoQueryRequest) SetCatalog(v string) {
	o.Catalog = &v
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *PrestoQueryRequest) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrestoQueryRequest) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *PrestoQueryRequest) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *PrestoQueryRequest) SetSchema(v string) {
	o.Schema = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *PrestoQueryRequest) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrestoQueryRequest) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *PrestoQueryRequest) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *PrestoQueryRequest) SetLimit(v int32) {
	o.Limit = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *PrestoQueryRequest) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrestoQueryRequest) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *PrestoQueryRequest) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *PrestoQueryRequest) SetOffset(v int32) {
	o.Offset = &v
}

func (o PrestoQueryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrestoQueryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Sql) {
		toSerialize["sql"] = o.Sql
	}
	if !IsNil(o.Catalog) {
		toSerialize["catalog"] = o.Catalog
	}
	if !IsNil(o.Schema) {
		toSerialize["schema"] = o.Schema
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	return toSerialize, nil
}

type NullablePrestoQueryRequest struct {
	value *PrestoQueryRequest
	isSet bool
}

func (v NullablePrestoQueryRequest) Get() *PrestoQueryRequest {
	return v.value
}

func (v *NullablePrestoQueryRequest) Set(val *PrestoQueryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePrestoQueryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePrestoQueryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrestoQueryRequest(val *PrestoQueryRequest) *NullablePrestoQueryRequest {
	return &NullablePrestoQueryRequest{value: val, isSet: true}
}

func (v NullablePrestoQueryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrestoQueryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


