/*
OpenAPI

OpenAPI

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package webrobot

import (
	"encoding/json"
)

// checks if the ImportOptionsDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImportOptionsDto{}

// ImportOptionsDto struct for ImportOptionsDto
type ImportOptionsDto struct {
	TargetOrganizationId *string `json:"targetOrganizationId,omitempty"`
	OverwriteExisting *bool `json:"overwriteExisting,omitempty"`
	ImportExistingProjects *bool `json:"importExistingProjects,omitempty"`
	ImportExistingAgents *bool `json:"importExistingAgents,omitempty"`
	ImportExistingJobs *bool `json:"importExistingJobs,omitempty"`
	ImportExistingTasks *bool `json:"importExistingTasks,omitempty"`
	ImportExistingDatasets *bool `json:"importExistingDatasets,omitempty"`
}

// NewImportOptionsDto instantiates a new ImportOptionsDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImportOptionsDto() *ImportOptionsDto {
	this := ImportOptionsDto{}
	return &this
}

// NewImportOptionsDtoWithDefaults instantiates a new ImportOptionsDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImportOptionsDtoWithDefaults() *ImportOptionsDto {
	this := ImportOptionsDto{}
	return &this
}

// GetTargetOrganizationId returns the TargetOrganizationId field value if set, zero value otherwise.
func (o *ImportOptionsDto) GetTargetOrganizationId() string {
	if o == nil || IsNil(o.TargetOrganizationId) {
		var ret string
		return ret
	}
	return *o.TargetOrganizationId
}

// GetTargetOrganizationIdOk returns a tuple with the TargetOrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportOptionsDto) GetTargetOrganizationIdOk() (*string, bool) {
	if o == nil || IsNil(o.TargetOrganizationId) {
		return nil, false
	}
	return o.TargetOrganizationId, true
}

// HasTargetOrganizationId returns a boolean if a field has been set.
func (o *ImportOptionsDto) HasTargetOrganizationId() bool {
	if o != nil && !IsNil(o.TargetOrganizationId) {
		return true
	}

	return false
}

// SetTargetOrganizationId gets a reference to the given string and assigns it to the TargetOrganizationId field.
func (o *ImportOptionsDto) SetTargetOrganizationId(v string) {
	o.TargetOrganizationId = &v
}

// GetOverwriteExisting returns the OverwriteExisting field value if set, zero value otherwise.
func (o *ImportOptionsDto) GetOverwriteExisting() bool {
	if o == nil || IsNil(o.OverwriteExisting) {
		var ret bool
		return ret
	}
	return *o.OverwriteExisting
}

// GetOverwriteExistingOk returns a tuple with the OverwriteExisting field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportOptionsDto) GetOverwriteExistingOk() (*bool, bool) {
	if o == nil || IsNil(o.OverwriteExisting) {
		return nil, false
	}
	return o.OverwriteExisting, true
}

// HasOverwriteExisting returns a boolean if a field has been set.
func (o *ImportOptionsDto) HasOverwriteExisting() bool {
	if o != nil && !IsNil(o.OverwriteExisting) {
		return true
	}

	return false
}

// SetOverwriteExisting gets a reference to the given bool and assigns it to the OverwriteExisting field.
func (o *ImportOptionsDto) SetOverwriteExisting(v bool) {
	o.OverwriteExisting = &v
}

// GetImportExistingProjects returns the ImportExistingProjects field value if set, zero value otherwise.
func (o *ImportOptionsDto) GetImportExistingProjects() bool {
	if o == nil || IsNil(o.ImportExistingProjects) {
		var ret bool
		return ret
	}
	return *o.ImportExistingProjects
}

// GetImportExistingProjectsOk returns a tuple with the ImportExistingProjects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportOptionsDto) GetImportExistingProjectsOk() (*bool, bool) {
	if o == nil || IsNil(o.ImportExistingProjects) {
		return nil, false
	}
	return o.ImportExistingProjects, true
}

// HasImportExistingProjects returns a boolean if a field has been set.
func (o *ImportOptionsDto) HasImportExistingProjects() bool {
	if o != nil && !IsNil(o.ImportExistingProjects) {
		return true
	}

	return false
}

// SetImportExistingProjects gets a reference to the given bool and assigns it to the ImportExistingProjects field.
func (o *ImportOptionsDto) SetImportExistingProjects(v bool) {
	o.ImportExistingProjects = &v
}

// GetImportExistingAgents returns the ImportExistingAgents field value if set, zero value otherwise.
func (o *ImportOptionsDto) GetImportExistingAgents() bool {
	if o == nil || IsNil(o.ImportExistingAgents) {
		var ret bool
		return ret
	}
	return *o.ImportExistingAgents
}

// GetImportExistingAgentsOk returns a tuple with the ImportExistingAgents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportOptionsDto) GetImportExistingAgentsOk() (*bool, bool) {
	if o == nil || IsNil(o.ImportExistingAgents) {
		return nil, false
	}
	return o.ImportExistingAgents, true
}

// HasImportExistingAgents returns a boolean if a field has been set.
func (o *ImportOptionsDto) HasImportExistingAgents() bool {
	if o != nil && !IsNil(o.ImportExistingAgents) {
		return true
	}

	return false
}

// SetImportExistingAgents gets a reference to the given bool and assigns it to the ImportExistingAgents field.
func (o *ImportOptionsDto) SetImportExistingAgents(v bool) {
	o.ImportExistingAgents = &v
}

// GetImportExistingJobs returns the ImportExistingJobs field value if set, zero value otherwise.
func (o *ImportOptionsDto) GetImportExistingJobs() bool {
	if o == nil || IsNil(o.ImportExistingJobs) {
		var ret bool
		return ret
	}
	return *o.ImportExistingJobs
}

// GetImportExistingJobsOk returns a tuple with the ImportExistingJobs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportOptionsDto) GetImportExistingJobsOk() (*bool, bool) {
	if o == nil || IsNil(o.ImportExistingJobs) {
		return nil, false
	}
	return o.ImportExistingJobs, true
}

// HasImportExistingJobs returns a boolean if a field has been set.
func (o *ImportOptionsDto) HasImportExistingJobs() bool {
	if o != nil && !IsNil(o.ImportExistingJobs) {
		return true
	}

	return false
}

// SetImportExistingJobs gets a reference to the given bool and assigns it to the ImportExistingJobs field.
func (o *ImportOptionsDto) SetImportExistingJobs(v bool) {
	o.ImportExistingJobs = &v
}

// GetImportExistingTasks returns the ImportExistingTasks field value if set, zero value otherwise.
func (o *ImportOptionsDto) GetImportExistingTasks() bool {
	if o == nil || IsNil(o.ImportExistingTasks) {
		var ret bool
		return ret
	}
	return *o.ImportExistingTasks
}

// GetImportExistingTasksOk returns a tuple with the ImportExistingTasks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportOptionsDto) GetImportExistingTasksOk() (*bool, bool) {
	if o == nil || IsNil(o.ImportExistingTasks) {
		return nil, false
	}
	return o.ImportExistingTasks, true
}

// HasImportExistingTasks returns a boolean if a field has been set.
func (o *ImportOptionsDto) HasImportExistingTasks() bool {
	if o != nil && !IsNil(o.ImportExistingTasks) {
		return true
	}

	return false
}

// SetImportExistingTasks gets a reference to the given bool and assigns it to the ImportExistingTasks field.
func (o *ImportOptionsDto) SetImportExistingTasks(v bool) {
	o.ImportExistingTasks = &v
}

// GetImportExistingDatasets returns the ImportExistingDatasets field value if set, zero value otherwise.
func (o *ImportOptionsDto) GetImportExistingDatasets() bool {
	if o == nil || IsNil(o.ImportExistingDatasets) {
		var ret bool
		return ret
	}
	return *o.ImportExistingDatasets
}

// GetImportExistingDatasetsOk returns a tuple with the ImportExistingDatasets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportOptionsDto) GetImportExistingDatasetsOk() (*bool, bool) {
	if o == nil || IsNil(o.ImportExistingDatasets) {
		return nil, false
	}
	return o.ImportExistingDatasets, true
}

// HasImportExistingDatasets returns a boolean if a field has been set.
func (o *ImportOptionsDto) HasImportExistingDatasets() bool {
	if o != nil && !IsNil(o.ImportExistingDatasets) {
		return true
	}

	return false
}

// SetImportExistingDatasets gets a reference to the given bool and assigns it to the ImportExistingDatasets field.
func (o *ImportOptionsDto) SetImportExistingDatasets(v bool) {
	o.ImportExistingDatasets = &v
}

func (o ImportOptionsDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImportOptionsDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TargetOrganizationId) {
		toSerialize["targetOrganizationId"] = o.TargetOrganizationId
	}
	if !IsNil(o.OverwriteExisting) {
		toSerialize["overwriteExisting"] = o.OverwriteExisting
	}
	if !IsNil(o.ImportExistingProjects) {
		toSerialize["importExistingProjects"] = o.ImportExistingProjects
	}
	if !IsNil(o.ImportExistingAgents) {
		toSerialize["importExistingAgents"] = o.ImportExistingAgents
	}
	if !IsNil(o.ImportExistingJobs) {
		toSerialize["importExistingJobs"] = o.ImportExistingJobs
	}
	if !IsNil(o.ImportExistingTasks) {
		toSerialize["importExistingTasks"] = o.ImportExistingTasks
	}
	if !IsNil(o.ImportExistingDatasets) {
		toSerialize["importExistingDatasets"] = o.ImportExistingDatasets
	}
	return toSerialize, nil
}

type NullableImportOptionsDto struct {
	value *ImportOptionsDto
	isSet bool
}

func (v NullableImportOptionsDto) Get() *ImportOptionsDto {
	return v.value
}

func (v *NullableImportOptionsDto) Set(val *ImportOptionsDto) {
	v.value = val
	v.isSet = true
}

func (v NullableImportOptionsDto) IsSet() bool {
	return v.isSet
}

func (v *NullableImportOptionsDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImportOptionsDto(val *ImportOptionsDto) *NullableImportOptionsDto {
	return &NullableImportOptionsDto{value: val, isSet: true}
}

func (v NullableImportOptionsDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImportOptionsDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


