# coding: utf-8

"""
    OpenAPI

    OpenAPI

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from webrobot.models.agentic_profile import AgenticProfile

class TestAgenticProfile(unittest.TestCase):
    """AgenticProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgenticProfile:
        """Test AgenticProfile
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgenticProfile`
        """
        model = AgenticProfile()
        if include_optional:
            return AgenticProfile(
                id = 56,
                name = '',
                version = '',
                description = '',
                organization_id = '',
                enabled = True,
                spec = '',
                spec_yaml = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by_id = 56
            )
        else:
            return AgenticProfile(
        )
        """

    def testAgenticProfile(self):
        """Test AgenticProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
