# coding: utf-8

"""
    OpenAPI

    OpenAPI

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from webrobot.models.model_publish_request import ModelPublishRequest

class TestModelPublishRequest(unittest.TestCase):
    """ModelPublishRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelPublishRequest:
        """Test ModelPublishRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelPublishRequest`
        """
        model = ModelPublishRequest()
        if include_optional:
            return ModelPublishRequest(
                local_model_path = '',
                model_name = '',
                description = ''
            )
        else:
            return ModelPublishRequest(
        )
        """

    def testModelPublishRequest(self):
        """Test ModelPublishRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
