# coding: utf-8

"""
    OpenAPI

    OpenAPI

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from webrobot.models.cloud_credential import CloudCredential

class TestCloudCredential(unittest.TestCase):
    """CloudCredential unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CloudCredential:
        """Test CloudCredential
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CloudCredential`
        """
        model = CloudCredential()
        if include_optional:
            return CloudCredential(
                id = 56,
                name = '',
                description = '',
                provider = 'OPENAI',
                api_key = '',
                api_secret = '',
                organization_id = '',
                project_id = '',
                region = '',
                endpoint = '',
                access_key_id = '',
                secret_access_key = '',
                session_token = '',
                account_id = '',
                subscription_id = '',
                resource_group = '',
                workspace_name = '',
                hugging_face_token = '',
                cohere_api_key = '',
                azure_ai_studio_endpoint = '',
                mosaicml_api_key = '',
                replicate_api_token = '',
                twitter_bearer_token = '',
                twitter_api_key = '',
                twitter_api_secret = '',
                reddit_client_id = '',
                reddit_client_secret = '',
                reddit_user_agent = '',
                facebook_access_token = '',
                facebook_app_id = '',
                facebook_app_secret = '',
                instagram_access_token = '',
                linkedin_access_token = '',
                linkedin_client_id = '',
                linkedin_client_secret = '',
                tiktok_client_key = '',
                tiktok_client_secret = '',
                youtube_api_key = '',
                databricks_workspace_url = '',
                databricks_access_token = '',
                databricks_cluster_id = '',
                oauth_access_token = '',
                oauth_refresh_token = '',
                oauth_token_expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                oauth_token_type = '',
                alphavantage_api_key = '',
                polygon_api_key = '',
                twelvedata_api_key = '',
                marketstack_access_key = '',
                fmp_api_key = '',
                iexcloud_token = '',
                cbond_api_key = '',
                cbond_client_id = '',
                cbond_client_secret = '',
                google_search_engine_id = '',
                bing_search_api_key = '',
                enabled = True
            )
        else:
            return CloudCredential(
        )
        """

    def testCloudCredential(self):
        """Test CloudCredential"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
