# coding: utf-8

"""
    OpenAPI

    OpenAPI

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from webrobot.models.form_data_content_disposition import FormDataContentDisposition

class TestFormDataContentDisposition(unittest.TestCase):
    """FormDataContentDisposition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FormDataContentDisposition:
        """Test FormDataContentDisposition
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FormDataContentDisposition`
        """
        model = FormDataContentDisposition()
        if include_optional:
            return FormDataContentDisposition(
                type = '',
                parameters = {
                    'key' : ''
                    },
                file_name = '',
                creation_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                modification_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                read_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                size = 56,
                name = ''
            )
        else:
            return FormDataContentDisposition(
        )
        """

    def testFormDataContentDisposition(self):
        """Test FormDataContentDisposition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
