# coding: utf-8

"""
    OpenAPI

    OpenAPI

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from webrobot.models.cron_job_request import CronJobRequest

class TestCronJobRequest(unittest.TestCase):
    """CronJobRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CronJobRequest:
        """Test CronJobRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CronJobRequest`
        """
        model = CronJobRequest()
        if include_optional:
            return CronJobRequest(
                name = '',
                namespace = '',
                schedule = '',
                webhook_url = '',
                job_id = '',
                project_id = '',
                cluster_provider = '',
                cluster_config_id = '',
                secret_name = '',
                secret_key = '',
                image = ''
            )
        else:
            return CronJobRequest(
        )
        """

    def testCronJobRequest(self):
        """Test CronJobRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
