# coding: utf-8

"""
    OpenAPI

    OpenAPI

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from webrobot.models.task_dto import TaskDto

class TestTaskDto(unittest.TestCase):
    """TaskDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaskDto:
        """Test TaskDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaskDto`
        """
        model = TaskDto()
        if include_optional:
            return TaskDto(
                id = '',
                name = '',
                description = '',
                job_id = '',
                bot_id = '',
                output_dataset_id = '',
                task_type = 'SPARK',
                execution_reference_id = '',
                execution_status = 'CREATED',
                execution_log = '',
                scheduled_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                execution_mode = 'MANUAL',
                enabled = True,
                api_key = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return TaskDto(
        )
        """

    def testTaskDto(self):
        """Test TaskDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
