# coding: utf-8

"""
    OpenAPI

    OpenAPI

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from webrobot.models.start_request import StartRequest

class TestStartRequest(unittest.TestCase):
    """StartRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StartRequest:
        """Test StartRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StartRequest`
        """
        model = StartRequest()
        if include_optional:
            return StartRequest(
                profile_id = 56,
                profile_name = '',
                profile_url = '',
                inputs = {
                    'key' : ''
                    },
                llm_provider = '',
                namespace = '',
                cluster_selector = '',
                image = '',
                working_dir = '',
                entrypoint = '',
                runtime_env_yaml = '',
                ttl_seconds = 56,
                active_deadline_seconds = 56,
                env_passthrough = {
                    'key' : ''
                    },
                organization_id = '',
                project_id = '',
                user_id = ''
            )
        else:
            return StartRequest(
        )
        """

    def testStartRequest(self):
        """Test StartRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
