# coding: utf-8

"""
    OpenAPI

    OpenAPI

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from webrobot.models.body_part_media_type import BodyPartMediaType

class TestBodyPartMediaType(unittest.TestCase):
    """BodyPartMediaType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BodyPartMediaType:
        """Test BodyPartMediaType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BodyPartMediaType`
        """
        model = BodyPartMediaType()
        if include_optional:
            return BodyPartMediaType(
                type = '',
                subtype = '',
                parameters = {
                    'key' : ''
                    },
                wildcard_type = True,
                wildcard_subtype = True
            )
        else:
            return BodyPartMediaType(
        )
        """

    def testBodyPartMediaType(self):
        """Test BodyPartMediaType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
