# coding: utf-8

"""
    OpenAPI

    OpenAPI

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from webrobot.models.body_part import BodyPart

class TestBodyPart(unittest.TestCase):
    """BodyPart unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BodyPart:
        """Test BodyPart
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BodyPart`
        """
        model = BodyPart()
        if include_optional:
            return BodyPart(
                content_disposition = webrobot.models.content_disposition.ContentDisposition(
                    type = '', 
                    parameters = {
                        'key' : ''
                        }, 
                    file_name = '', 
                    creation_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    modification_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    read_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    size = 56, ),
                entity = None,
                headers = {
                    'key' : [
                        ''
                        ]
                    },
                media_type = webrobot.models.body_part_media_type.BodyPart_mediaType(
                    type = '', 
                    subtype = '', 
                    parameters = {
                        'key' : ''
                        }, 
                    wildcard_type = True, 
                    wildcard_subtype = True, ),
                message_body_workers = None,
                parent = webrobot.models.multi_part.MultiPart(
                    content_disposition = webrobot.models.content_disposition.ContentDisposition(
                        type = '', 
                        parameters = {
                            'key' : ''
                            }, 
                        file_name = '', 
                        creation_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        modification_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        read_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        size = 56, ), 
                    entity = webrobot.models.entity.entity(), 
                    headers = {
                        'key' : [
                            ''
                            ]
                        }, 
                    media_type = webrobot.models.body_part_media_type.BodyPart_mediaType(
                        type = '', 
                        subtype = '', 
                        wildcard_type = True, 
                        wildcard_subtype = True, ), 
                    message_body_workers = webrobot.models.message_body_workers.MessageBodyWorkers(), 
                    parent = webrobot.models.multi_part.MultiPart(
                        entity = webrobot.models.entity.entity(), 
                        providers = webrobot.models.providers.providers(), 
                        body_parts = [
                            webrobot.models.body_part.BodyPart(
                                entity = webrobot.models.entity.entity(), 
                                providers = webrobot.models.providers.providers(), 
                                parameterized_headers = {
                                    'key' : [
                                        webrobot.models.parameterized_header.ParameterizedHeader(
                                            value = '', )
                                        ]
                                    }, )
                            ], 
                        parameterized_headers = {
                            'key' : [
                                webrobot.models.parameterized_header.ParameterizedHeader(
                                    value = '', )
                                ]
                            }, ), 
                    providers = webrobot.models.providers.providers(), 
                    body_parts = [
                        webrobot.models.body_part.BodyPart(
                            entity = webrobot.models.entity.entity(), 
                            providers = webrobot.models.providers.providers(), )
                        ], 
                    parameterized_headers = , ),
                providers = webrobot.models.providers.providers(),
                parameterized_headers = {
                    'key' : [
                        webrobot.models.parameterized_header.ParameterizedHeader(
                            value = '', 
                            parameters = {
                                'key' : ''
                                }, )
                        ]
                    }
            )
        else:
            return BodyPart(
        )
        """

    def testBodyPart(self):
        """Test BodyPart"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
