# coding: utf-8

"""
    OpenAPI

    OpenAPI

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from webrobot.models.copy_to_organizations_dto import CopyToOrganizationsDto

class TestCopyToOrganizationsDto(unittest.TestCase):
    """CopyToOrganizationsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CopyToOrganizationsDto:
        """Test CopyToOrganizationsDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CopyToOrganizationsDto`
        """
        model = CopyToOrganizationsDto()
        if include_optional:
            return CopyToOrganizationsDto(
                organization_ids = [
                    ''
                    ]
            )
        else:
            return CopyToOrganizationsDto(
        )
        """

    def testCopyToOrganizationsDto(self):
        """Test CopyToOrganizationsDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
