# coding: utf-8

"""
    OpenAPI

    OpenAPI

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from webrobot.models.agent_dto import AgentDto

class TestAgentDto(unittest.TestCase):
    """AgentDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentDto:
        """Test AgentDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentDto`
        """
        model = AgentDto()
        if include_optional:
            return AgentDto(
                id = '',
                name = '',
                description = '',
                enabled = True,
                api_endpoint = '',
                execution_mode = 'MANUAL',
                category_id = '',
                type = 'SCRAPING_AGENT',
                role = '',
                backstory = '',
                default_prompt = '',
                prompts = '',
                config = '',
                code = '',
                code_type_id = '',
                pyspark_code = '',
                python_extensions = '',
                stack_type = '',
                generated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                tool_ids = [
                    ''
                    ],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return AgentDto(
        )
        """

    def testAgentDto(self):
        """Test AgentDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
