# coding: utf-8

"""
    OpenAPI

    OpenAPI

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from webrobot.models.import_options_dto import ImportOptionsDto

class TestImportOptionsDto(unittest.TestCase):
    """ImportOptionsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImportOptionsDto:
        """Test ImportOptionsDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImportOptionsDto`
        """
        model = ImportOptionsDto()
        if include_optional:
            return ImportOptionsDto(
                target_organization_id = '',
                overwrite_existing = True,
                import_existing_projects = True,
                import_existing_agents = True,
                import_existing_jobs = True,
                import_existing_tasks = True,
                import_existing_datasets = True
            )
        else:
            return ImportOptionsDto(
        )
        """

    def testImportOptionsDto(self):
        """Test ImportOptionsDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
