/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobCategoryDto
 */
export interface JobCategoryDto {
    /**
     * 
     * @type {string}
     * @memberof JobCategoryDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof JobCategoryDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof JobCategoryDto
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof JobCategoryDto
     */
    icon?: string;
    /**
     * 
     * @type {string}
     * @memberof JobCategoryDto
     */
    visibility?: JobCategoryDtoVisibilityEnum;
    /**
     * 
     * @type {boolean}
     * @memberof JobCategoryDto
     */
    enabled?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof JobCategoryDto
     */
    agentIds?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof JobCategoryDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof JobCategoryDto
     */
    updatedAt?: Date;
}


/**
 * @export
 */
export const JobCategoryDtoVisibilityEnum = {
    Public: 'PUBLIC',
    Private: 'PRIVATE'
} as const;
export type JobCategoryDtoVisibilityEnum = typeof JobCategoryDtoVisibilityEnum[keyof typeof JobCategoryDtoVisibilityEnum];


/**
 * Check if a given object implements the JobCategoryDto interface.
 */
export function instanceOfJobCategoryDto(value: object): value is JobCategoryDto {
    return true;
}

export function JobCategoryDtoFromJSON(json: any): JobCategoryDto {
    return JobCategoryDtoFromJSONTyped(json, false);
}

export function JobCategoryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobCategoryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'visibility': json['visibility'] == null ? undefined : json['visibility'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'agentIds': json['agentIds'] == null ? undefined : json['agentIds'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function JobCategoryDtoToJSON(json: any): JobCategoryDto {
    return JobCategoryDtoToJSONTyped(json, false);
}

export function JobCategoryDtoToJSONTyped(value?: JobCategoryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'icon': value['icon'],
        'visibility': value['visibility'],
        'enabled': value['enabled'],
        'agentIds': value['agentIds'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

