/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobDto
 */
export interface JobDto {
    /**
     * 
     * @type {string}
     * @memberof JobDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof JobDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof JobDto
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof JobDto
     */
    projectId?: string;
    /**
     * 
     * @type {string}
     * @memberof JobDto
     */
    agentId?: string;
    /**
     * 
     * @type {string}
     * @memberof JobDto
     */
    inputDatasetId?: string;
    /**
     * 
     * @type {string}
     * @memberof JobDto
     */
    executionStatus?: JobDtoExecutionStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof JobDto
     */
    scheduledTime?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof JobDto
     */
    enabled?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof JobDto
     */
    taskIds?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof JobDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof JobDto
     */
    updatedAt?: Date;
}


/**
 * @export
 */
export const JobDtoExecutionStatusEnum = {
    Pending: 'PENDING',
    Running: 'RUNNING',
    Completed: 'COMPLETED',
    Failed: 'FAILED'
} as const;
export type JobDtoExecutionStatusEnum = typeof JobDtoExecutionStatusEnum[keyof typeof JobDtoExecutionStatusEnum];


/**
 * Check if a given object implements the JobDto interface.
 */
export function instanceOfJobDto(value: object): value is JobDto {
    return true;
}

export function JobDtoFromJSON(json: any): JobDto {
    return JobDtoFromJSONTyped(json, false);
}

export function JobDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'agentId': json['agentId'] == null ? undefined : json['agentId'],
        'inputDatasetId': json['inputDatasetId'] == null ? undefined : json['inputDatasetId'],
        'executionStatus': json['executionStatus'] == null ? undefined : json['executionStatus'],
        'scheduledTime': json['scheduledTime'] == null ? undefined : (new Date(json['scheduledTime'])),
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'taskIds': json['taskIds'] == null ? undefined : json['taskIds'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function JobDtoToJSON(json: any): JobDto {
    return JobDtoToJSONTyped(json, false);
}

export function JobDtoToJSONTyped(value?: JobDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'projectId': value['projectId'],
        'agentId': value['agentId'],
        'inputDatasetId': value['inputDatasetId'],
        'executionStatus': value['executionStatus'],
        'scheduledTime': value['scheduledTime'] == null ? value['scheduledTime'] : value['scheduledTime'].toISOString(),
        'enabled': value['enabled'],
        'taskIds': value['taskIds'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

