/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectScheduleRequest
 */
export interface ProjectScheduleRequest {
    /**
     * 
     * @type {string}
     * @memberof ProjectScheduleRequest
     */
    cronSchedule?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectScheduleRequest
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProjectScheduleRequest
     */
    timezone?: string;
}

/**
 * Check if a given object implements the ProjectScheduleRequest interface.
 */
export function instanceOfProjectScheduleRequest(value: object): value is ProjectScheduleRequest {
    return true;
}

export function ProjectScheduleRequestFromJSON(json: any): ProjectScheduleRequest {
    return ProjectScheduleRequestFromJSONTyped(json, false);
}

export function ProjectScheduleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectScheduleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'cronSchedule': json['cronSchedule'] == null ? undefined : json['cronSchedule'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
    };
}

export function ProjectScheduleRequestToJSON(json: any): ProjectScheduleRequest {
    return ProjectScheduleRequestToJSONTyped(json, false);
}

export function ProjectScheduleRequestToJSONTyped(value?: ProjectScheduleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cronSchedule': value['cronSchedule'],
        'enabled': value['enabled'],
        'timezone': value['timezone'],
    };
}

