/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskDto
 */
export interface TaskDto {
    /**
     * 
     * @type {string}
     * @memberof TaskDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskDto
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskDto
     */
    jobId?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskDto
     */
    botId?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskDto
     */
    outputDatasetId?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskDto
     */
    taskType?: TaskDtoTaskTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof TaskDto
     */
    executionReferenceId?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskDto
     */
    executionStatus?: TaskDtoExecutionStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof TaskDto
     */
    executionLog?: string;
    /**
     * 
     * @type {Date}
     * @memberof TaskDto
     */
    scheduledTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof TaskDto
     */
    executionMode?: TaskDtoExecutionModeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof TaskDto
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TaskDto
     */
    apiKey?: string;
    /**
     * 
     * @type {Date}
     * @memberof TaskDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TaskDto
     */
    updatedAt?: Date;
}


/**
 * @export
 */
export const TaskDtoTaskTypeEnum = {
    Spark: 'SPARK',
    AutonomousAgent: 'AUTONOMOUS_AGENT',
    BackgroundTask: 'BACKGROUND_TASK'
} as const;
export type TaskDtoTaskTypeEnum = typeof TaskDtoTaskTypeEnum[keyof typeof TaskDtoTaskTypeEnum];

/**
 * @export
 */
export const TaskDtoExecutionStatusEnum = {
    Pending: 'PENDING',
    Running: 'RUNNING',
    Completed: 'COMPLETED',
    Failed: 'FAILED'
} as const;
export type TaskDtoExecutionStatusEnum = typeof TaskDtoExecutionStatusEnum[keyof typeof TaskDtoExecutionStatusEnum];

/**
 * @export
 */
export const TaskDtoExecutionModeEnum = {
    Manual: 'MANUAL',
    Scheduled: 'SCHEDULED',
    EventDriven: 'EVENT_DRIVEN'
} as const;
export type TaskDtoExecutionModeEnum = typeof TaskDtoExecutionModeEnum[keyof typeof TaskDtoExecutionModeEnum];


/**
 * Check if a given object implements the TaskDto interface.
 */
export function instanceOfTaskDto(value: object): value is TaskDto {
    return true;
}

export function TaskDtoFromJSON(json: any): TaskDto {
    return TaskDtoFromJSONTyped(json, false);
}

export function TaskDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'jobId': json['jobId'] == null ? undefined : json['jobId'],
        'botId': json['botId'] == null ? undefined : json['botId'],
        'outputDatasetId': json['outputDatasetId'] == null ? undefined : json['outputDatasetId'],
        'taskType': json['taskType'] == null ? undefined : json['taskType'],
        'executionReferenceId': json['executionReferenceId'] == null ? undefined : json['executionReferenceId'],
        'executionStatus': json['executionStatus'] == null ? undefined : json['executionStatus'],
        'executionLog': json['executionLog'] == null ? undefined : json['executionLog'],
        'scheduledTime': json['scheduledTime'] == null ? undefined : (new Date(json['scheduledTime'])),
        'executionMode': json['executionMode'] == null ? undefined : json['executionMode'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'apiKey': json['apiKey'] == null ? undefined : json['apiKey'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function TaskDtoToJSON(json: any): TaskDto {
    return TaskDtoToJSONTyped(json, false);
}

export function TaskDtoToJSONTyped(value?: TaskDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'jobId': value['jobId'],
        'botId': value['botId'],
        'outputDatasetId': value['outputDatasetId'],
        'taskType': value['taskType'],
        'executionReferenceId': value['executionReferenceId'],
        'executionStatus': value['executionStatus'],
        'executionLog': value['executionLog'],
        'scheduledTime': value['scheduledTime'] == null ? value['scheduledTime'] : value['scheduledTime'].toISOString(),
        'executionMode': value['executionMode'],
        'enabled': value['enabled'],
        'apiKey': value['apiKey'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

