# coding: utf-8

"""
    OpenAPI

    OpenAPI

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CloudCredential(BaseModel):
    """
    CloudCredential
    """ # noqa: E501
    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    provider: Optional[StrictStr] = None
    api_key: Optional[StrictStr] = Field(default=None, alias="apiKey")
    api_secret: Optional[StrictStr] = Field(default=None, alias="apiSecret")
    organization_id: Optional[StrictStr] = Field(default=None, alias="organizationId")
    project_id: Optional[StrictStr] = Field(default=None, alias="projectId")
    region: Optional[StrictStr] = None
    endpoint: Optional[StrictStr] = None
    access_key_id: Optional[StrictStr] = Field(default=None, alias="accessKeyId")
    secret_access_key: Optional[StrictStr] = Field(default=None, alias="secretAccessKey")
    session_token: Optional[StrictStr] = Field(default=None, alias="sessionToken")
    account_id: Optional[StrictStr] = Field(default=None, alias="accountId")
    subscription_id: Optional[StrictStr] = Field(default=None, alias="subscriptionId")
    resource_group: Optional[StrictStr] = Field(default=None, alias="resourceGroup")
    workspace_name: Optional[StrictStr] = Field(default=None, alias="workspaceName")
    hugging_face_token: Optional[StrictStr] = Field(default=None, alias="huggingFaceToken")
    cohere_api_key: Optional[StrictStr] = Field(default=None, alias="cohereApiKey")
    azure_ai_studio_endpoint: Optional[StrictStr] = Field(default=None, alias="azureAiStudioEndpoint")
    mosaicml_api_key: Optional[StrictStr] = Field(default=None, alias="mosaicmlApiKey")
    replicate_api_token: Optional[StrictStr] = Field(default=None, alias="replicateApiToken")
    twitter_bearer_token: Optional[StrictStr] = Field(default=None, alias="twitterBearerToken")
    twitter_api_key: Optional[StrictStr] = Field(default=None, alias="twitterApiKey")
    twitter_api_secret: Optional[StrictStr] = Field(default=None, alias="twitterApiSecret")
    reddit_client_id: Optional[StrictStr] = Field(default=None, alias="redditClientId")
    reddit_client_secret: Optional[StrictStr] = Field(default=None, alias="redditClientSecret")
    reddit_user_agent: Optional[StrictStr] = Field(default=None, alias="redditUserAgent")
    facebook_access_token: Optional[StrictStr] = Field(default=None, alias="facebookAccessToken")
    facebook_app_id: Optional[StrictStr] = Field(default=None, alias="facebookAppId")
    facebook_app_secret: Optional[StrictStr] = Field(default=None, alias="facebookAppSecret")
    instagram_access_token: Optional[StrictStr] = Field(default=None, alias="instagramAccessToken")
    linkedin_access_token: Optional[StrictStr] = Field(default=None, alias="linkedinAccessToken")
    linkedin_client_id: Optional[StrictStr] = Field(default=None, alias="linkedinClientId")
    linkedin_client_secret: Optional[StrictStr] = Field(default=None, alias="linkedinClientSecret")
    tiktok_client_key: Optional[StrictStr] = Field(default=None, alias="tiktokClientKey")
    tiktok_client_secret: Optional[StrictStr] = Field(default=None, alias="tiktokClientSecret")
    youtube_api_key: Optional[StrictStr] = Field(default=None, alias="youtubeApiKey")
    databricks_workspace_url: Optional[StrictStr] = Field(default=None, alias="databricksWorkspaceUrl")
    databricks_access_token: Optional[StrictStr] = Field(default=None, alias="databricksAccessToken")
    databricks_cluster_id: Optional[StrictStr] = Field(default=None, alias="databricksClusterId")
    oauth_access_token: Optional[StrictStr] = Field(default=None, alias="oauthAccessToken")
    oauth_refresh_token: Optional[StrictStr] = Field(default=None, alias="oauthRefreshToken")
    oauth_token_expires_at: Optional[datetime] = Field(default=None, alias="oauthTokenExpiresAt")
    oauth_token_type: Optional[StrictStr] = Field(default=None, alias="oauthTokenType")
    alphavantage_api_key: Optional[StrictStr] = Field(default=None, alias="alphavantageApiKey")
    polygon_api_key: Optional[StrictStr] = Field(default=None, alias="polygonApiKey")
    twelvedata_api_key: Optional[StrictStr] = Field(default=None, alias="twelvedataApiKey")
    marketstack_access_key: Optional[StrictStr] = Field(default=None, alias="marketstackAccessKey")
    fmp_api_key: Optional[StrictStr] = Field(default=None, alias="fmpApiKey")
    iexcloud_token: Optional[StrictStr] = Field(default=None, alias="iexcloudToken")
    cbond_api_key: Optional[StrictStr] = Field(default=None, alias="cbondApiKey")
    cbond_client_id: Optional[StrictStr] = Field(default=None, alias="cbondClientId")
    cbond_client_secret: Optional[StrictStr] = Field(default=None, alias="cbondClientSecret")
    google_search_engine_id: Optional[StrictStr] = Field(default=None, alias="googleSearchEngineId")
    bing_search_api_key: Optional[StrictStr] = Field(default=None, alias="bingSearchApiKey")
    enabled: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["id", "name", "description", "provider", "apiKey", "apiSecret", "organizationId", "projectId", "region", "endpoint", "accessKeyId", "secretAccessKey", "sessionToken", "accountId", "subscriptionId", "resourceGroup", "workspaceName", "huggingFaceToken", "cohereApiKey", "azureAiStudioEndpoint", "mosaicmlApiKey", "replicateApiToken", "twitterBearerToken", "twitterApiKey", "twitterApiSecret", "redditClientId", "redditClientSecret", "redditUserAgent", "facebookAccessToken", "facebookAppId", "facebookAppSecret", "instagramAccessToken", "linkedinAccessToken", "linkedinClientId", "linkedinClientSecret", "tiktokClientKey", "tiktokClientSecret", "youtubeApiKey", "databricksWorkspaceUrl", "databricksAccessToken", "databricksClusterId", "oauthAccessToken", "oauthRefreshToken", "oauthTokenExpiresAt", "oauthTokenType", "alphavantageApiKey", "polygonApiKey", "twelvedataApiKey", "marketstackAccessKey", "fmpApiKey", "iexcloudToken", "cbondApiKey", "cbondClientId", "cbondClientSecret", "googleSearchEngineId", "bingSearchApiKey", "enabled"]

    @field_validator('provider')
    def provider_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['OPENAI', 'ANTHROPIC', 'HUGGING_FACE', 'COHERE', 'AZURE_AI_STUDIO', 'MOSAICML', 'REPLIC', 'STEEL_DEV', 'TOGETHERAI', 'GROQ', 'AWS', 'AZURE', 'GCP', 'HETZNER', 'AWS_BEDROCK', 'GOOGLE_VERTEX', 'DATABRICKS', 'LLAMACLOUD', 'WEAVIATE', 'TWITTER', 'REDDIT', 'FACEBOOK', 'INSTAGRAM', 'LINKEDIN', 'TIKTOK', 'YOUTUBE', 'ALPHAVANTAGE', 'POLYGON', 'TWELVEDATA', 'MARKETSTACK', 'FMP', 'IEXCLOUD', 'CBOND', 'GOOGLE_SEARCH', 'BING_SEARCH', 'DATAIMPULSE', 'BRIGHTDATA', 'SMARTPROXY', 'OXYLABS', 'IPROXY', 'THORDATA', 'PROXYROTATOR', 'CUSTOM']):
            raise ValueError("must be one of enum values ('OPENAI', 'ANTHROPIC', 'HUGGING_FACE', 'COHERE', 'AZURE_AI_STUDIO', 'MOSAICML', 'REPLIC', 'STEEL_DEV', 'TOGETHERAI', 'GROQ', 'AWS', 'AZURE', 'GCP', 'HETZNER', 'AWS_BEDROCK', 'GOOGLE_VERTEX', 'DATABRICKS', 'LLAMACLOUD', 'WEAVIATE', 'TWITTER', 'REDDIT', 'FACEBOOK', 'INSTAGRAM', 'LINKEDIN', 'TIKTOK', 'YOUTUBE', 'ALPHAVANTAGE', 'POLYGON', 'TWELVEDATA', 'MARKETSTACK', 'FMP', 'IEXCLOUD', 'CBOND', 'GOOGLE_SEARCH', 'BING_SEARCH', 'DATAIMPULSE', 'BRIGHTDATA', 'SMARTPROXY', 'OXYLABS', 'IPROXY', 'THORDATA', 'PROXYROTATOR', 'CUSTOM')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CloudCredential from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CloudCredential from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "provider": obj.get("provider"),
            "apiKey": obj.get("apiKey"),
            "apiSecret": obj.get("apiSecret"),
            "organizationId": obj.get("organizationId"),
            "projectId": obj.get("projectId"),
            "region": obj.get("region"),
            "endpoint": obj.get("endpoint"),
            "accessKeyId": obj.get("accessKeyId"),
            "secretAccessKey": obj.get("secretAccessKey"),
            "sessionToken": obj.get("sessionToken"),
            "accountId": obj.get("accountId"),
            "subscriptionId": obj.get("subscriptionId"),
            "resourceGroup": obj.get("resourceGroup"),
            "workspaceName": obj.get("workspaceName"),
            "huggingFaceToken": obj.get("huggingFaceToken"),
            "cohereApiKey": obj.get("cohereApiKey"),
            "azureAiStudioEndpoint": obj.get("azureAiStudioEndpoint"),
            "mosaicmlApiKey": obj.get("mosaicmlApiKey"),
            "replicateApiToken": obj.get("replicateApiToken"),
            "twitterBearerToken": obj.get("twitterBearerToken"),
            "twitterApiKey": obj.get("twitterApiKey"),
            "twitterApiSecret": obj.get("twitterApiSecret"),
            "redditClientId": obj.get("redditClientId"),
            "redditClientSecret": obj.get("redditClientSecret"),
            "redditUserAgent": obj.get("redditUserAgent"),
            "facebookAccessToken": obj.get("facebookAccessToken"),
            "facebookAppId": obj.get("facebookAppId"),
            "facebookAppSecret": obj.get("facebookAppSecret"),
            "instagramAccessToken": obj.get("instagramAccessToken"),
            "linkedinAccessToken": obj.get("linkedinAccessToken"),
            "linkedinClientId": obj.get("linkedinClientId"),
            "linkedinClientSecret": obj.get("linkedinClientSecret"),
            "tiktokClientKey": obj.get("tiktokClientKey"),
            "tiktokClientSecret": obj.get("tiktokClientSecret"),
            "youtubeApiKey": obj.get("youtubeApiKey"),
            "databricksWorkspaceUrl": obj.get("databricksWorkspaceUrl"),
            "databricksAccessToken": obj.get("databricksAccessToken"),
            "databricksClusterId": obj.get("databricksClusterId"),
            "oauthAccessToken": obj.get("oauthAccessToken"),
            "oauthRefreshToken": obj.get("oauthRefreshToken"),
            "oauthTokenExpiresAt": obj.get("oauthTokenExpiresAt"),
            "oauthTokenType": obj.get("oauthTokenType"),
            "alphavantageApiKey": obj.get("alphavantageApiKey"),
            "polygonApiKey": obj.get("polygonApiKey"),
            "twelvedataApiKey": obj.get("twelvedataApiKey"),
            "marketstackAccessKey": obj.get("marketstackAccessKey"),
            "fmpApiKey": obj.get("fmpApiKey"),
            "iexcloudToken": obj.get("iexcloudToken"),
            "cbondApiKey": obj.get("cbondApiKey"),
            "cbondClientId": obj.get("cbondClientId"),
            "cbondClientSecret": obj.get("cbondClientSecret"),
            "googleSearchEngineId": obj.get("googleSearchEngineId"),
            "bingSearchApiKey": obj.get("bingSearchApiKey"),
            "enabled": obj.get("enabled")
        })
        return _obj


