# coding: utf-8

"""
    OpenAPI

    OpenAPI

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class StartRequest(BaseModel):
    """
    StartRequest
    """ # noqa: E501
    profile_id: Optional[StrictInt] = Field(default=None, alias="profileId")
    profile_name: Optional[StrictStr] = Field(default=None, alias="profileName")
    profile_url: Optional[StrictStr] = Field(default=None, alias="profileUrl")
    inputs: Optional[Dict[str, StrictStr]] = None
    llm_provider: Optional[StrictStr] = Field(default=None, alias="llmProvider")
    namespace: Optional[StrictStr] = None
    cluster_selector: Optional[StrictStr] = Field(default=None, alias="clusterSelector")
    image: Optional[StrictStr] = None
    working_dir: Optional[StrictStr] = Field(default=None, alias="workingDir")
    entrypoint: Optional[StrictStr] = None
    runtime_env_yaml: Optional[StrictStr] = Field(default=None, alias="runtimeEnvYaml")
    ttl_seconds: Optional[StrictInt] = Field(default=None, alias="ttlSeconds")
    active_deadline_seconds: Optional[StrictInt] = Field(default=None, alias="activeDeadlineSeconds")
    env_passthrough: Optional[Dict[str, StrictStr]] = Field(default=None, alias="envPassthrough")
    organization_id: Optional[StrictStr] = Field(default=None, alias="organizationId")
    project_id: Optional[StrictStr] = Field(default=None, alias="projectId")
    user_id: Optional[StrictStr] = Field(default=None, alias="userId")
    __properties: ClassVar[List[str]] = ["profileId", "profileName", "profileUrl", "inputs", "llmProvider", "namespace", "clusterSelector", "image", "workingDir", "entrypoint", "runtimeEnvYaml", "ttlSeconds", "activeDeadlineSeconds", "envPassthrough", "organizationId", "projectId", "userId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StartRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StartRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "profileId": obj.get("profileId"),
            "profileName": obj.get("profileName"),
            "profileUrl": obj.get("profileUrl"),
            "inputs": obj.get("inputs"),
            "llmProvider": obj.get("llmProvider"),
            "namespace": obj.get("namespace"),
            "clusterSelector": obj.get("clusterSelector"),
            "image": obj.get("image"),
            "workingDir": obj.get("workingDir"),
            "entrypoint": obj.get("entrypoint"),
            "runtimeEnvYaml": obj.get("runtimeEnvYaml"),
            "ttlSeconds": obj.get("ttlSeconds"),
            "activeDeadlineSeconds": obj.get("activeDeadlineSeconds"),
            "envPassthrough": obj.get("envPassthrough"),
            "organizationId": obj.get("organizationId"),
            "projectId": obj.get("projectId"),
            "userId": obj.get("userId")
        })
        return _obj


