<?php
/**
 * AgentDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenAPI
 *
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * AgentDto Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AgentDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AgentDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'name' => 'string',
        'description' => 'string',
        'enabled' => 'bool',
        'api_endpoint' => 'string',
        'execution_mode' => 'string',
        'category_id' => 'string',
        'type' => 'string',
        'role' => 'string',
        'backstory' => 'string',
        'default_prompt' => 'string',
        'prompts' => 'string',
        'config' => 'string',
        'code' => 'string',
        'code_type_id' => 'string',
        'pyspark_code' => 'string',
        'python_extensions' => 'string',
        'stack_type' => 'string',
        'generated_at' => '\DateTime',
        'tool_ids' => 'string[]',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'name' => null,
        'description' => null,
        'enabled' => null,
        'api_endpoint' => null,
        'execution_mode' => null,
        'category_id' => null,
        'type' => null,
        'role' => null,
        'backstory' => null,
        'default_prompt' => null,
        'prompts' => null,
        'config' => null,
        'code' => null,
        'code_type_id' => null,
        'pyspark_code' => null,
        'python_extensions' => null,
        'stack_type' => null,
        'generated_at' => 'date-time',
        'tool_ids' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'name' => false,
        'description' => false,
        'enabled' => false,
        'api_endpoint' => false,
        'execution_mode' => false,
        'category_id' => false,
        'type' => false,
        'role' => false,
        'backstory' => false,
        'default_prompt' => false,
        'prompts' => false,
        'config' => false,
        'code' => false,
        'code_type_id' => false,
        'pyspark_code' => false,
        'python_extensions' => false,
        'stack_type' => false,
        'generated_at' => false,
        'tool_ids' => false,
        'created_at' => false,
        'updated_at' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'description' => 'description',
        'enabled' => 'enabled',
        'api_endpoint' => 'apiEndpoint',
        'execution_mode' => 'executionMode',
        'category_id' => 'categoryId',
        'type' => 'type',
        'role' => 'role',
        'backstory' => 'backstory',
        'default_prompt' => 'defaultPrompt',
        'prompts' => 'prompts',
        'config' => 'config',
        'code' => 'code',
        'code_type_id' => 'codeTypeId',
        'pyspark_code' => 'pysparkCode',
        'python_extensions' => 'pythonExtensions',
        'stack_type' => 'stackType',
        'generated_at' => 'generatedAt',
        'tool_ids' => 'toolIds',
        'created_at' => 'createdAt',
        'updated_at' => 'updatedAt'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'description' => 'setDescription',
        'enabled' => 'setEnabled',
        'api_endpoint' => 'setApiEndpoint',
        'execution_mode' => 'setExecutionMode',
        'category_id' => 'setCategoryId',
        'type' => 'setType',
        'role' => 'setRole',
        'backstory' => 'setBackstory',
        'default_prompt' => 'setDefaultPrompt',
        'prompts' => 'setPrompts',
        'config' => 'setConfig',
        'code' => 'setCode',
        'code_type_id' => 'setCodeTypeId',
        'pyspark_code' => 'setPysparkCode',
        'python_extensions' => 'setPythonExtensions',
        'stack_type' => 'setStackType',
        'generated_at' => 'setGeneratedAt',
        'tool_ids' => 'setToolIds',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'description' => 'getDescription',
        'enabled' => 'getEnabled',
        'api_endpoint' => 'getApiEndpoint',
        'execution_mode' => 'getExecutionMode',
        'category_id' => 'getCategoryId',
        'type' => 'getType',
        'role' => 'getRole',
        'backstory' => 'getBackstory',
        'default_prompt' => 'getDefaultPrompt',
        'prompts' => 'getPrompts',
        'config' => 'getConfig',
        'code' => 'getCode',
        'code_type_id' => 'getCodeTypeId',
        'pyspark_code' => 'getPysparkCode',
        'python_extensions' => 'getPythonExtensions',
        'stack_type' => 'getStackType',
        'generated_at' => 'getGeneratedAt',
        'tool_ids' => 'getToolIds',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const EXECUTION_MODE_MANUAL = 'MANUAL';
    public const EXECUTION_MODE_SCHEDULED = 'SCHEDULED';
    public const EXECUTION_MODE_EVENT_DRIVEN = 'EVENT_DRIVEN';
    public const TYPE_SCRAPING_AGENT = 'SCRAPING_AGENT';
    public const TYPE_LEADGEN_AGENT = 'LEADGEN_AGENT';
    public const TYPE_TRADING_AGENT = 'TRADING_AGENT';
    public const TYPE_DATA_ANALYTICS_AGENT = 'DATA_ANALYTICS_AGENT';
    public const TYPE_REPORTING_AGENT = 'REPORTING_AGENT';
    public const TYPE_ML_AGENT = 'ML_AGENT';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getExecutionModeAllowableValues()
    {
        return [
            self::EXECUTION_MODE_MANUAL,
            self::EXECUTION_MODE_SCHEDULED,
            self::EXECUTION_MODE_EVENT_DRIVEN,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_SCRAPING_AGENT,
            self::TYPE_LEADGEN_AGENT,
            self::TYPE_TRADING_AGENT,
            self::TYPE_DATA_ANALYTICS_AGENT,
            self::TYPE_REPORTING_AGENT,
            self::TYPE_ML_AGENT,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('enabled', $data ?? [], null);
        $this->setIfExists('api_endpoint', $data ?? [], null);
        $this->setIfExists('execution_mode', $data ?? [], null);
        $this->setIfExists('category_id', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('role', $data ?? [], null);
        $this->setIfExists('backstory', $data ?? [], null);
        $this->setIfExists('default_prompt', $data ?? [], null);
        $this->setIfExists('prompts', $data ?? [], null);
        $this->setIfExists('config', $data ?? [], null);
        $this->setIfExists('code', $data ?? [], null);
        $this->setIfExists('code_type_id', $data ?? [], null);
        $this->setIfExists('pyspark_code', $data ?? [], null);
        $this->setIfExists('python_extensions', $data ?? [], null);
        $this->setIfExists('stack_type', $data ?? [], null);
        $this->setIfExists('generated_at', $data ?? [], null);
        $this->setIfExists('tool_ids', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getExecutionModeAllowableValues();
        if (!is_null($this->container['execution_mode']) && !in_array($this->container['execution_mode'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'execution_mode', must be one of '%s'",
                $this->container['execution_mode'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'type', must be one of '%s'",
                $this->container['type'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets enabled
     *
     * @return bool|null
     */
    public function getEnabled()
    {
        return $this->container['enabled'];
    }

    /**
     * Sets enabled
     *
     * @param bool|null $enabled enabled
     *
     * @return self
     */
    public function setEnabled($enabled)
    {
        if (is_null($enabled)) {
            throw new \InvalidArgumentException('non-nullable enabled cannot be null');
        }
        $this->container['enabled'] = $enabled;

        return $this;
    }

    /**
     * Gets api_endpoint
     *
     * @return string|null
     */
    public function getApiEndpoint()
    {
        return $this->container['api_endpoint'];
    }

    /**
     * Sets api_endpoint
     *
     * @param string|null $api_endpoint api_endpoint
     *
     * @return self
     */
    public function setApiEndpoint($api_endpoint)
    {
        if (is_null($api_endpoint)) {
            throw new \InvalidArgumentException('non-nullable api_endpoint cannot be null');
        }
        $this->container['api_endpoint'] = $api_endpoint;

        return $this;
    }

    /**
     * Gets execution_mode
     *
     * @return string|null
     */
    public function getExecutionMode()
    {
        return $this->container['execution_mode'];
    }

    /**
     * Sets execution_mode
     *
     * @param string|null $execution_mode execution_mode
     *
     * @return self
     */
    public function setExecutionMode($execution_mode)
    {
        if (is_null($execution_mode)) {
            throw new \InvalidArgumentException('non-nullable execution_mode cannot be null');
        }
        $allowedValues = $this->getExecutionModeAllowableValues();
        if (!in_array($execution_mode, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'execution_mode', must be one of '%s'",
                    $execution_mode,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['execution_mode'] = $execution_mode;

        return $this;
    }

    /**
     * Gets category_id
     *
     * @return string|null
     */
    public function getCategoryId()
    {
        return $this->container['category_id'];
    }

    /**
     * Sets category_id
     *
     * @param string|null $category_id category_id
     *
     * @return self
     */
    public function setCategoryId($category_id)
    {
        if (is_null($category_id)) {
            throw new \InvalidArgumentException('non-nullable category_id cannot be null');
        }
        $this->container['category_id'] = $category_id;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'type', must be one of '%s'",
                    $type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets role
     *
     * @return string|null
     */
    public function getRole()
    {
        return $this->container['role'];
    }

    /**
     * Sets role
     *
     * @param string|null $role role
     *
     * @return self
     */
    public function setRole($role)
    {
        if (is_null($role)) {
            throw new \InvalidArgumentException('non-nullable role cannot be null');
        }
        $this->container['role'] = $role;

        return $this;
    }

    /**
     * Gets backstory
     *
     * @return string|null
     */
    public function getBackstory()
    {
        return $this->container['backstory'];
    }

    /**
     * Sets backstory
     *
     * @param string|null $backstory backstory
     *
     * @return self
     */
    public function setBackstory($backstory)
    {
        if (is_null($backstory)) {
            throw new \InvalidArgumentException('non-nullable backstory cannot be null');
        }
        $this->container['backstory'] = $backstory;

        return $this;
    }

    /**
     * Gets default_prompt
     *
     * @return string|null
     */
    public function getDefaultPrompt()
    {
        return $this->container['default_prompt'];
    }

    /**
     * Sets default_prompt
     *
     * @param string|null $default_prompt default_prompt
     *
     * @return self
     */
    public function setDefaultPrompt($default_prompt)
    {
        if (is_null($default_prompt)) {
            throw new \InvalidArgumentException('non-nullable default_prompt cannot be null');
        }
        $this->container['default_prompt'] = $default_prompt;

        return $this;
    }

    /**
     * Gets prompts
     *
     * @return string|null
     */
    public function getPrompts()
    {
        return $this->container['prompts'];
    }

    /**
     * Sets prompts
     *
     * @param string|null $prompts prompts
     *
     * @return self
     */
    public function setPrompts($prompts)
    {
        if (is_null($prompts)) {
            throw new \InvalidArgumentException('non-nullable prompts cannot be null');
        }
        $this->container['prompts'] = $prompts;

        return $this;
    }

    /**
     * Gets config
     *
     * @return string|null
     */
    public function getConfig()
    {
        return $this->container['config'];
    }

    /**
     * Sets config
     *
     * @param string|null $config config
     *
     * @return self
     */
    public function setConfig($config)
    {
        if (is_null($config)) {
            throw new \InvalidArgumentException('non-nullable config cannot be null');
        }
        $this->container['config'] = $config;

        return $this;
    }

    /**
     * Gets code
     *
     * @return string|null
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string|null $code code
     *
     * @return self
     */
    public function setCode($code)
    {
        if (is_null($code)) {
            throw new \InvalidArgumentException('non-nullable code cannot be null');
        }
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets code_type_id
     *
     * @return string|null
     */
    public function getCodeTypeId()
    {
        return $this->container['code_type_id'];
    }

    /**
     * Sets code_type_id
     *
     * @param string|null $code_type_id code_type_id
     *
     * @return self
     */
    public function setCodeTypeId($code_type_id)
    {
        if (is_null($code_type_id)) {
            throw new \InvalidArgumentException('non-nullable code_type_id cannot be null');
        }
        $this->container['code_type_id'] = $code_type_id;

        return $this;
    }

    /**
     * Gets pyspark_code
     *
     * @return string|null
     */
    public function getPysparkCode()
    {
        return $this->container['pyspark_code'];
    }

    /**
     * Sets pyspark_code
     *
     * @param string|null $pyspark_code pyspark_code
     *
     * @return self
     */
    public function setPysparkCode($pyspark_code)
    {
        if (is_null($pyspark_code)) {
            throw new \InvalidArgumentException('non-nullable pyspark_code cannot be null');
        }
        $this->container['pyspark_code'] = $pyspark_code;

        return $this;
    }

    /**
     * Gets python_extensions
     *
     * @return string|null
     */
    public function getPythonExtensions()
    {
        return $this->container['python_extensions'];
    }

    /**
     * Sets python_extensions
     *
     * @param string|null $python_extensions python_extensions
     *
     * @return self
     */
    public function setPythonExtensions($python_extensions)
    {
        if (is_null($python_extensions)) {
            throw new \InvalidArgumentException('non-nullable python_extensions cannot be null');
        }
        $this->container['python_extensions'] = $python_extensions;

        return $this;
    }

    /**
     * Gets stack_type
     *
     * @return string|null
     */
    public function getStackType()
    {
        return $this->container['stack_type'];
    }

    /**
     * Sets stack_type
     *
     * @param string|null $stack_type stack_type
     *
     * @return self
     */
    public function setStackType($stack_type)
    {
        if (is_null($stack_type)) {
            throw new \InvalidArgumentException('non-nullable stack_type cannot be null');
        }
        $this->container['stack_type'] = $stack_type;

        return $this;
    }

    /**
     * Gets generated_at
     *
     * @return \DateTime|null
     */
    public function getGeneratedAt()
    {
        return $this->container['generated_at'];
    }

    /**
     * Sets generated_at
     *
     * @param \DateTime|null $generated_at generated_at
     *
     * @return self
     */
    public function setGeneratedAt($generated_at)
    {
        if (is_null($generated_at)) {
            throw new \InvalidArgumentException('non-nullable generated_at cannot be null');
        }
        $this->container['generated_at'] = $generated_at;

        return $this;
    }

    /**
     * Gets tool_ids
     *
     * @return string[]|null
     */
    public function getToolIds()
    {
        return $this->container['tool_ids'];
    }

    /**
     * Sets tool_ids
     *
     * @param string[]|null $tool_ids tool_ids
     *
     * @return self
     */
    public function setToolIds($tool_ids)
    {
        if (is_null($tool_ids)) {
            throw new \InvalidArgumentException('non-nullable tool_ids cannot be null');
        }
        $this->container['tool_ids'] = $tool_ids;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime|null $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime|null $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


