<?php
/**
 * CloudCredential
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenAPI
 *
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CloudCredential Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CloudCredential implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CloudCredential';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'name' => 'string',
        'description' => 'string',
        'provider' => 'string',
        'api_key' => 'string',
        'api_secret' => 'string',
        'organization_id' => 'string',
        'project_id' => 'string',
        'region' => 'string',
        'endpoint' => 'string',
        'access_key_id' => 'string',
        'secret_access_key' => 'string',
        'session_token' => 'string',
        'account_id' => 'string',
        'subscription_id' => 'string',
        'resource_group' => 'string',
        'workspace_name' => 'string',
        'hugging_face_token' => 'string',
        'cohere_api_key' => 'string',
        'azure_ai_studio_endpoint' => 'string',
        'mosaicml_api_key' => 'string',
        'replicate_api_token' => 'string',
        'twitter_bearer_token' => 'string',
        'twitter_api_key' => 'string',
        'twitter_api_secret' => 'string',
        'reddit_client_id' => 'string',
        'reddit_client_secret' => 'string',
        'reddit_user_agent' => 'string',
        'facebook_access_token' => 'string',
        'facebook_app_id' => 'string',
        'facebook_app_secret' => 'string',
        'instagram_access_token' => 'string',
        'linkedin_access_token' => 'string',
        'linkedin_client_id' => 'string',
        'linkedin_client_secret' => 'string',
        'tiktok_client_key' => 'string',
        'tiktok_client_secret' => 'string',
        'youtube_api_key' => 'string',
        'databricks_workspace_url' => 'string',
        'databricks_access_token' => 'string',
        'databricks_cluster_id' => 'string',
        'oauth_access_token' => 'string',
        'oauth_refresh_token' => 'string',
        'oauth_token_expires_at' => '\DateTime',
        'oauth_token_type' => 'string',
        'alphavantage_api_key' => 'string',
        'polygon_api_key' => 'string',
        'twelvedata_api_key' => 'string',
        'marketstack_access_key' => 'string',
        'fmp_api_key' => 'string',
        'iexcloud_token' => 'string',
        'cbond_api_key' => 'string',
        'cbond_client_id' => 'string',
        'cbond_client_secret' => 'string',
        'google_search_engine_id' => 'string',
        'bing_search_api_key' => 'string',
        'enabled' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'int32',
        'name' => null,
        'description' => null,
        'provider' => null,
        'api_key' => null,
        'api_secret' => null,
        'organization_id' => null,
        'project_id' => null,
        'region' => null,
        'endpoint' => null,
        'access_key_id' => null,
        'secret_access_key' => null,
        'session_token' => null,
        'account_id' => null,
        'subscription_id' => null,
        'resource_group' => null,
        'workspace_name' => null,
        'hugging_face_token' => null,
        'cohere_api_key' => null,
        'azure_ai_studio_endpoint' => null,
        'mosaicml_api_key' => null,
        'replicate_api_token' => null,
        'twitter_bearer_token' => null,
        'twitter_api_key' => null,
        'twitter_api_secret' => null,
        'reddit_client_id' => null,
        'reddit_client_secret' => null,
        'reddit_user_agent' => null,
        'facebook_access_token' => null,
        'facebook_app_id' => null,
        'facebook_app_secret' => null,
        'instagram_access_token' => null,
        'linkedin_access_token' => null,
        'linkedin_client_id' => null,
        'linkedin_client_secret' => null,
        'tiktok_client_key' => null,
        'tiktok_client_secret' => null,
        'youtube_api_key' => null,
        'databricks_workspace_url' => null,
        'databricks_access_token' => null,
        'databricks_cluster_id' => null,
        'oauth_access_token' => null,
        'oauth_refresh_token' => null,
        'oauth_token_expires_at' => 'date-time',
        'oauth_token_type' => null,
        'alphavantage_api_key' => null,
        'polygon_api_key' => null,
        'twelvedata_api_key' => null,
        'marketstack_access_key' => null,
        'fmp_api_key' => null,
        'iexcloud_token' => null,
        'cbond_api_key' => null,
        'cbond_client_id' => null,
        'cbond_client_secret' => null,
        'google_search_engine_id' => null,
        'bing_search_api_key' => null,
        'enabled' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'name' => false,
        'description' => false,
        'provider' => false,
        'api_key' => false,
        'api_secret' => false,
        'organization_id' => false,
        'project_id' => false,
        'region' => false,
        'endpoint' => false,
        'access_key_id' => false,
        'secret_access_key' => false,
        'session_token' => false,
        'account_id' => false,
        'subscription_id' => false,
        'resource_group' => false,
        'workspace_name' => false,
        'hugging_face_token' => false,
        'cohere_api_key' => false,
        'azure_ai_studio_endpoint' => false,
        'mosaicml_api_key' => false,
        'replicate_api_token' => false,
        'twitter_bearer_token' => false,
        'twitter_api_key' => false,
        'twitter_api_secret' => false,
        'reddit_client_id' => false,
        'reddit_client_secret' => false,
        'reddit_user_agent' => false,
        'facebook_access_token' => false,
        'facebook_app_id' => false,
        'facebook_app_secret' => false,
        'instagram_access_token' => false,
        'linkedin_access_token' => false,
        'linkedin_client_id' => false,
        'linkedin_client_secret' => false,
        'tiktok_client_key' => false,
        'tiktok_client_secret' => false,
        'youtube_api_key' => false,
        'databricks_workspace_url' => false,
        'databricks_access_token' => false,
        'databricks_cluster_id' => false,
        'oauth_access_token' => false,
        'oauth_refresh_token' => false,
        'oauth_token_expires_at' => false,
        'oauth_token_type' => false,
        'alphavantage_api_key' => false,
        'polygon_api_key' => false,
        'twelvedata_api_key' => false,
        'marketstack_access_key' => false,
        'fmp_api_key' => false,
        'iexcloud_token' => false,
        'cbond_api_key' => false,
        'cbond_client_id' => false,
        'cbond_client_secret' => false,
        'google_search_engine_id' => false,
        'bing_search_api_key' => false,
        'enabled' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'description' => 'description',
        'provider' => 'provider',
        'api_key' => 'apiKey',
        'api_secret' => 'apiSecret',
        'organization_id' => 'organizationId',
        'project_id' => 'projectId',
        'region' => 'region',
        'endpoint' => 'endpoint',
        'access_key_id' => 'accessKeyId',
        'secret_access_key' => 'secretAccessKey',
        'session_token' => 'sessionToken',
        'account_id' => 'accountId',
        'subscription_id' => 'subscriptionId',
        'resource_group' => 'resourceGroup',
        'workspace_name' => 'workspaceName',
        'hugging_face_token' => 'huggingFaceToken',
        'cohere_api_key' => 'cohereApiKey',
        'azure_ai_studio_endpoint' => 'azureAiStudioEndpoint',
        'mosaicml_api_key' => 'mosaicmlApiKey',
        'replicate_api_token' => 'replicateApiToken',
        'twitter_bearer_token' => 'twitterBearerToken',
        'twitter_api_key' => 'twitterApiKey',
        'twitter_api_secret' => 'twitterApiSecret',
        'reddit_client_id' => 'redditClientId',
        'reddit_client_secret' => 'redditClientSecret',
        'reddit_user_agent' => 'redditUserAgent',
        'facebook_access_token' => 'facebookAccessToken',
        'facebook_app_id' => 'facebookAppId',
        'facebook_app_secret' => 'facebookAppSecret',
        'instagram_access_token' => 'instagramAccessToken',
        'linkedin_access_token' => 'linkedinAccessToken',
        'linkedin_client_id' => 'linkedinClientId',
        'linkedin_client_secret' => 'linkedinClientSecret',
        'tiktok_client_key' => 'tiktokClientKey',
        'tiktok_client_secret' => 'tiktokClientSecret',
        'youtube_api_key' => 'youtubeApiKey',
        'databricks_workspace_url' => 'databricksWorkspaceUrl',
        'databricks_access_token' => 'databricksAccessToken',
        'databricks_cluster_id' => 'databricksClusterId',
        'oauth_access_token' => 'oauthAccessToken',
        'oauth_refresh_token' => 'oauthRefreshToken',
        'oauth_token_expires_at' => 'oauthTokenExpiresAt',
        'oauth_token_type' => 'oauthTokenType',
        'alphavantage_api_key' => 'alphavantageApiKey',
        'polygon_api_key' => 'polygonApiKey',
        'twelvedata_api_key' => 'twelvedataApiKey',
        'marketstack_access_key' => 'marketstackAccessKey',
        'fmp_api_key' => 'fmpApiKey',
        'iexcloud_token' => 'iexcloudToken',
        'cbond_api_key' => 'cbondApiKey',
        'cbond_client_id' => 'cbondClientId',
        'cbond_client_secret' => 'cbondClientSecret',
        'google_search_engine_id' => 'googleSearchEngineId',
        'bing_search_api_key' => 'bingSearchApiKey',
        'enabled' => 'enabled'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'description' => 'setDescription',
        'provider' => 'setProvider',
        'api_key' => 'setApiKey',
        'api_secret' => 'setApiSecret',
        'organization_id' => 'setOrganizationId',
        'project_id' => 'setProjectId',
        'region' => 'setRegion',
        'endpoint' => 'setEndpoint',
        'access_key_id' => 'setAccessKeyId',
        'secret_access_key' => 'setSecretAccessKey',
        'session_token' => 'setSessionToken',
        'account_id' => 'setAccountId',
        'subscription_id' => 'setSubscriptionId',
        'resource_group' => 'setResourceGroup',
        'workspace_name' => 'setWorkspaceName',
        'hugging_face_token' => 'setHuggingFaceToken',
        'cohere_api_key' => 'setCohereApiKey',
        'azure_ai_studio_endpoint' => 'setAzureAiStudioEndpoint',
        'mosaicml_api_key' => 'setMosaicmlApiKey',
        'replicate_api_token' => 'setReplicateApiToken',
        'twitter_bearer_token' => 'setTwitterBearerToken',
        'twitter_api_key' => 'setTwitterApiKey',
        'twitter_api_secret' => 'setTwitterApiSecret',
        'reddit_client_id' => 'setRedditClientId',
        'reddit_client_secret' => 'setRedditClientSecret',
        'reddit_user_agent' => 'setRedditUserAgent',
        'facebook_access_token' => 'setFacebookAccessToken',
        'facebook_app_id' => 'setFacebookAppId',
        'facebook_app_secret' => 'setFacebookAppSecret',
        'instagram_access_token' => 'setInstagramAccessToken',
        'linkedin_access_token' => 'setLinkedinAccessToken',
        'linkedin_client_id' => 'setLinkedinClientId',
        'linkedin_client_secret' => 'setLinkedinClientSecret',
        'tiktok_client_key' => 'setTiktokClientKey',
        'tiktok_client_secret' => 'setTiktokClientSecret',
        'youtube_api_key' => 'setYoutubeApiKey',
        'databricks_workspace_url' => 'setDatabricksWorkspaceUrl',
        'databricks_access_token' => 'setDatabricksAccessToken',
        'databricks_cluster_id' => 'setDatabricksClusterId',
        'oauth_access_token' => 'setOauthAccessToken',
        'oauth_refresh_token' => 'setOauthRefreshToken',
        'oauth_token_expires_at' => 'setOauthTokenExpiresAt',
        'oauth_token_type' => 'setOauthTokenType',
        'alphavantage_api_key' => 'setAlphavantageApiKey',
        'polygon_api_key' => 'setPolygonApiKey',
        'twelvedata_api_key' => 'setTwelvedataApiKey',
        'marketstack_access_key' => 'setMarketstackAccessKey',
        'fmp_api_key' => 'setFmpApiKey',
        'iexcloud_token' => 'setIexcloudToken',
        'cbond_api_key' => 'setCbondApiKey',
        'cbond_client_id' => 'setCbondClientId',
        'cbond_client_secret' => 'setCbondClientSecret',
        'google_search_engine_id' => 'setGoogleSearchEngineId',
        'bing_search_api_key' => 'setBingSearchApiKey',
        'enabled' => 'setEnabled'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'description' => 'getDescription',
        'provider' => 'getProvider',
        'api_key' => 'getApiKey',
        'api_secret' => 'getApiSecret',
        'organization_id' => 'getOrganizationId',
        'project_id' => 'getProjectId',
        'region' => 'getRegion',
        'endpoint' => 'getEndpoint',
        'access_key_id' => 'getAccessKeyId',
        'secret_access_key' => 'getSecretAccessKey',
        'session_token' => 'getSessionToken',
        'account_id' => 'getAccountId',
        'subscription_id' => 'getSubscriptionId',
        'resource_group' => 'getResourceGroup',
        'workspace_name' => 'getWorkspaceName',
        'hugging_face_token' => 'getHuggingFaceToken',
        'cohere_api_key' => 'getCohereApiKey',
        'azure_ai_studio_endpoint' => 'getAzureAiStudioEndpoint',
        'mosaicml_api_key' => 'getMosaicmlApiKey',
        'replicate_api_token' => 'getReplicateApiToken',
        'twitter_bearer_token' => 'getTwitterBearerToken',
        'twitter_api_key' => 'getTwitterApiKey',
        'twitter_api_secret' => 'getTwitterApiSecret',
        'reddit_client_id' => 'getRedditClientId',
        'reddit_client_secret' => 'getRedditClientSecret',
        'reddit_user_agent' => 'getRedditUserAgent',
        'facebook_access_token' => 'getFacebookAccessToken',
        'facebook_app_id' => 'getFacebookAppId',
        'facebook_app_secret' => 'getFacebookAppSecret',
        'instagram_access_token' => 'getInstagramAccessToken',
        'linkedin_access_token' => 'getLinkedinAccessToken',
        'linkedin_client_id' => 'getLinkedinClientId',
        'linkedin_client_secret' => 'getLinkedinClientSecret',
        'tiktok_client_key' => 'getTiktokClientKey',
        'tiktok_client_secret' => 'getTiktokClientSecret',
        'youtube_api_key' => 'getYoutubeApiKey',
        'databricks_workspace_url' => 'getDatabricksWorkspaceUrl',
        'databricks_access_token' => 'getDatabricksAccessToken',
        'databricks_cluster_id' => 'getDatabricksClusterId',
        'oauth_access_token' => 'getOauthAccessToken',
        'oauth_refresh_token' => 'getOauthRefreshToken',
        'oauth_token_expires_at' => 'getOauthTokenExpiresAt',
        'oauth_token_type' => 'getOauthTokenType',
        'alphavantage_api_key' => 'getAlphavantageApiKey',
        'polygon_api_key' => 'getPolygonApiKey',
        'twelvedata_api_key' => 'getTwelvedataApiKey',
        'marketstack_access_key' => 'getMarketstackAccessKey',
        'fmp_api_key' => 'getFmpApiKey',
        'iexcloud_token' => 'getIexcloudToken',
        'cbond_api_key' => 'getCbondApiKey',
        'cbond_client_id' => 'getCbondClientId',
        'cbond_client_secret' => 'getCbondClientSecret',
        'google_search_engine_id' => 'getGoogleSearchEngineId',
        'bing_search_api_key' => 'getBingSearchApiKey',
        'enabled' => 'getEnabled'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const PROVIDER_OPENAI = 'OPENAI';
    public const PROVIDER_ANTHROPIC = 'ANTHROPIC';
    public const PROVIDER_HUGGING_FACE = 'HUGGING_FACE';
    public const PROVIDER_COHERE = 'COHERE';
    public const PROVIDER_AZURE_AI_STUDIO = 'AZURE_AI_STUDIO';
    public const PROVIDER_MOSAICML = 'MOSAICML';
    public const PROVIDER_REPLIC = 'REPLIC';
    public const PROVIDER_STEEL_DEV = 'STEEL_DEV';
    public const PROVIDER_TOGETHERAI = 'TOGETHERAI';
    public const PROVIDER_GROQ = 'GROQ';
    public const PROVIDER_AWS = 'AWS';
    public const PROVIDER_AZURE = 'AZURE';
    public const PROVIDER_GCP = 'GCP';
    public const PROVIDER_HETZNER = 'HETZNER';
    public const PROVIDER_AWS_BEDROCK = 'AWS_BEDROCK';
    public const PROVIDER_GOOGLE_VERTEX = 'GOOGLE_VERTEX';
    public const PROVIDER_DATABRICKS = 'DATABRICKS';
    public const PROVIDER_LLAMACLOUD = 'LLAMACLOUD';
    public const PROVIDER_WEAVIATE = 'WEAVIATE';
    public const PROVIDER_TWITTER = 'TWITTER';
    public const PROVIDER_REDDIT = 'REDDIT';
    public const PROVIDER_FACEBOOK = 'FACEBOOK';
    public const PROVIDER_INSTAGRAM = 'INSTAGRAM';
    public const PROVIDER_LINKEDIN = 'LINKEDIN';
    public const PROVIDER_TIKTOK = 'TIKTOK';
    public const PROVIDER_YOUTUBE = 'YOUTUBE';
    public const PROVIDER_ALPHAVANTAGE = 'ALPHAVANTAGE';
    public const PROVIDER_POLYGON = 'POLYGON';
    public const PROVIDER_TWELVEDATA = 'TWELVEDATA';
    public const PROVIDER_MARKETSTACK = 'MARKETSTACK';
    public const PROVIDER_FMP = 'FMP';
    public const PROVIDER_IEXCLOUD = 'IEXCLOUD';
    public const PROVIDER_CBOND = 'CBOND';
    public const PROVIDER_GOOGLE_SEARCH = 'GOOGLE_SEARCH';
    public const PROVIDER_BING_SEARCH = 'BING_SEARCH';
    public const PROVIDER_DATAIMPULSE = 'DATAIMPULSE';
    public const PROVIDER_BRIGHTDATA = 'BRIGHTDATA';
    public const PROVIDER_SMARTPROXY = 'SMARTPROXY';
    public const PROVIDER_OXYLABS = 'OXYLABS';
    public const PROVIDER_IPROXY = 'IPROXY';
    public const PROVIDER_THORDATA = 'THORDATA';
    public const PROVIDER_PROXYROTATOR = 'PROXYROTATOR';
    public const PROVIDER_CUSTOM = 'CUSTOM';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getProviderAllowableValues()
    {
        return [
            self::PROVIDER_OPENAI,
            self::PROVIDER_ANTHROPIC,
            self::PROVIDER_HUGGING_FACE,
            self::PROVIDER_COHERE,
            self::PROVIDER_AZURE_AI_STUDIO,
            self::PROVIDER_MOSAICML,
            self::PROVIDER_REPLIC,
            self::PROVIDER_STEEL_DEV,
            self::PROVIDER_TOGETHERAI,
            self::PROVIDER_GROQ,
            self::PROVIDER_AWS,
            self::PROVIDER_AZURE,
            self::PROVIDER_GCP,
            self::PROVIDER_HETZNER,
            self::PROVIDER_AWS_BEDROCK,
            self::PROVIDER_GOOGLE_VERTEX,
            self::PROVIDER_DATABRICKS,
            self::PROVIDER_LLAMACLOUD,
            self::PROVIDER_WEAVIATE,
            self::PROVIDER_TWITTER,
            self::PROVIDER_REDDIT,
            self::PROVIDER_FACEBOOK,
            self::PROVIDER_INSTAGRAM,
            self::PROVIDER_LINKEDIN,
            self::PROVIDER_TIKTOK,
            self::PROVIDER_YOUTUBE,
            self::PROVIDER_ALPHAVANTAGE,
            self::PROVIDER_POLYGON,
            self::PROVIDER_TWELVEDATA,
            self::PROVIDER_MARKETSTACK,
            self::PROVIDER_FMP,
            self::PROVIDER_IEXCLOUD,
            self::PROVIDER_CBOND,
            self::PROVIDER_GOOGLE_SEARCH,
            self::PROVIDER_BING_SEARCH,
            self::PROVIDER_DATAIMPULSE,
            self::PROVIDER_BRIGHTDATA,
            self::PROVIDER_SMARTPROXY,
            self::PROVIDER_OXYLABS,
            self::PROVIDER_IPROXY,
            self::PROVIDER_THORDATA,
            self::PROVIDER_PROXYROTATOR,
            self::PROVIDER_CUSTOM,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('provider', $data ?? [], null);
        $this->setIfExists('api_key', $data ?? [], null);
        $this->setIfExists('api_secret', $data ?? [], null);
        $this->setIfExists('organization_id', $data ?? [], null);
        $this->setIfExists('project_id', $data ?? [], null);
        $this->setIfExists('region', $data ?? [], null);
        $this->setIfExists('endpoint', $data ?? [], null);
        $this->setIfExists('access_key_id', $data ?? [], null);
        $this->setIfExists('secret_access_key', $data ?? [], null);
        $this->setIfExists('session_token', $data ?? [], null);
        $this->setIfExists('account_id', $data ?? [], null);
        $this->setIfExists('subscription_id', $data ?? [], null);
        $this->setIfExists('resource_group', $data ?? [], null);
        $this->setIfExists('workspace_name', $data ?? [], null);
        $this->setIfExists('hugging_face_token', $data ?? [], null);
        $this->setIfExists('cohere_api_key', $data ?? [], null);
        $this->setIfExists('azure_ai_studio_endpoint', $data ?? [], null);
        $this->setIfExists('mosaicml_api_key', $data ?? [], null);
        $this->setIfExists('replicate_api_token', $data ?? [], null);
        $this->setIfExists('twitter_bearer_token', $data ?? [], null);
        $this->setIfExists('twitter_api_key', $data ?? [], null);
        $this->setIfExists('twitter_api_secret', $data ?? [], null);
        $this->setIfExists('reddit_client_id', $data ?? [], null);
        $this->setIfExists('reddit_client_secret', $data ?? [], null);
        $this->setIfExists('reddit_user_agent', $data ?? [], null);
        $this->setIfExists('facebook_access_token', $data ?? [], null);
        $this->setIfExists('facebook_app_id', $data ?? [], null);
        $this->setIfExists('facebook_app_secret', $data ?? [], null);
        $this->setIfExists('instagram_access_token', $data ?? [], null);
        $this->setIfExists('linkedin_access_token', $data ?? [], null);
        $this->setIfExists('linkedin_client_id', $data ?? [], null);
        $this->setIfExists('linkedin_client_secret', $data ?? [], null);
        $this->setIfExists('tiktok_client_key', $data ?? [], null);
        $this->setIfExists('tiktok_client_secret', $data ?? [], null);
        $this->setIfExists('youtube_api_key', $data ?? [], null);
        $this->setIfExists('databricks_workspace_url', $data ?? [], null);
        $this->setIfExists('databricks_access_token', $data ?? [], null);
        $this->setIfExists('databricks_cluster_id', $data ?? [], null);
        $this->setIfExists('oauth_access_token', $data ?? [], null);
        $this->setIfExists('oauth_refresh_token', $data ?? [], null);
        $this->setIfExists('oauth_token_expires_at', $data ?? [], null);
        $this->setIfExists('oauth_token_type', $data ?? [], null);
        $this->setIfExists('alphavantage_api_key', $data ?? [], null);
        $this->setIfExists('polygon_api_key', $data ?? [], null);
        $this->setIfExists('twelvedata_api_key', $data ?? [], null);
        $this->setIfExists('marketstack_access_key', $data ?? [], null);
        $this->setIfExists('fmp_api_key', $data ?? [], null);
        $this->setIfExists('iexcloud_token', $data ?? [], null);
        $this->setIfExists('cbond_api_key', $data ?? [], null);
        $this->setIfExists('cbond_client_id', $data ?? [], null);
        $this->setIfExists('cbond_client_secret', $data ?? [], null);
        $this->setIfExists('google_search_engine_id', $data ?? [], null);
        $this->setIfExists('bing_search_api_key', $data ?? [], null);
        $this->setIfExists('enabled', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getProviderAllowableValues();
        if (!is_null($this->container['provider']) && !in_array($this->container['provider'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'provider', must be one of '%s'",
                $this->container['provider'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets provider
     *
     * @return string|null
     */
    public function getProvider()
    {
        return $this->container['provider'];
    }

    /**
     * Sets provider
     *
     * @param string|null $provider provider
     *
     * @return self
     */
    public function setProvider($provider)
    {
        if (is_null($provider)) {
            throw new \InvalidArgumentException('non-nullable provider cannot be null');
        }
        $allowedValues = $this->getProviderAllowableValues();
        if (!in_array($provider, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'provider', must be one of '%s'",
                    $provider,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['provider'] = $provider;

        return $this;
    }

    /**
     * Gets api_key
     *
     * @return string|null
     */
    public function getApiKey()
    {
        return $this->container['api_key'];
    }

    /**
     * Sets api_key
     *
     * @param string|null $api_key api_key
     *
     * @return self
     */
    public function setApiKey($api_key)
    {
        if (is_null($api_key)) {
            throw new \InvalidArgumentException('non-nullable api_key cannot be null');
        }
        $this->container['api_key'] = $api_key;

        return $this;
    }

    /**
     * Gets api_secret
     *
     * @return string|null
     */
    public function getApiSecret()
    {
        return $this->container['api_secret'];
    }

    /**
     * Sets api_secret
     *
     * @param string|null $api_secret api_secret
     *
     * @return self
     */
    public function setApiSecret($api_secret)
    {
        if (is_null($api_secret)) {
            throw new \InvalidArgumentException('non-nullable api_secret cannot be null');
        }
        $this->container['api_secret'] = $api_secret;

        return $this;
    }

    /**
     * Gets organization_id
     *
     * @return string|null
     */
    public function getOrganizationId()
    {
        return $this->container['organization_id'];
    }

    /**
     * Sets organization_id
     *
     * @param string|null $organization_id organization_id
     *
     * @return self
     */
    public function setOrganizationId($organization_id)
    {
        if (is_null($organization_id)) {
            throw new \InvalidArgumentException('non-nullable organization_id cannot be null');
        }
        $this->container['organization_id'] = $organization_id;

        return $this;
    }

    /**
     * Gets project_id
     *
     * @return string|null
     */
    public function getProjectId()
    {
        return $this->container['project_id'];
    }

    /**
     * Sets project_id
     *
     * @param string|null $project_id project_id
     *
     * @return self
     */
    public function setProjectId($project_id)
    {
        if (is_null($project_id)) {
            throw new \InvalidArgumentException('non-nullable project_id cannot be null');
        }
        $this->container['project_id'] = $project_id;

        return $this;
    }

    /**
     * Gets region
     *
     * @return string|null
     */
    public function getRegion()
    {
        return $this->container['region'];
    }

    /**
     * Sets region
     *
     * @param string|null $region region
     *
     * @return self
     */
    public function setRegion($region)
    {
        if (is_null($region)) {
            throw new \InvalidArgumentException('non-nullable region cannot be null');
        }
        $this->container['region'] = $region;

        return $this;
    }

    /**
     * Gets endpoint
     *
     * @return string|null
     */
    public function getEndpoint()
    {
        return $this->container['endpoint'];
    }

    /**
     * Sets endpoint
     *
     * @param string|null $endpoint endpoint
     *
     * @return self
     */
    public function setEndpoint($endpoint)
    {
        if (is_null($endpoint)) {
            throw new \InvalidArgumentException('non-nullable endpoint cannot be null');
        }
        $this->container['endpoint'] = $endpoint;

        return $this;
    }

    /**
     * Gets access_key_id
     *
     * @return string|null
     */
    public function getAccessKeyId()
    {
        return $this->container['access_key_id'];
    }

    /**
     * Sets access_key_id
     *
     * @param string|null $access_key_id access_key_id
     *
     * @return self
     */
    public function setAccessKeyId($access_key_id)
    {
        if (is_null($access_key_id)) {
            throw new \InvalidArgumentException('non-nullable access_key_id cannot be null');
        }
        $this->container['access_key_id'] = $access_key_id;

        return $this;
    }

    /**
     * Gets secret_access_key
     *
     * @return string|null
     */
    public function getSecretAccessKey()
    {
        return $this->container['secret_access_key'];
    }

    /**
     * Sets secret_access_key
     *
     * @param string|null $secret_access_key secret_access_key
     *
     * @return self
     */
    public function setSecretAccessKey($secret_access_key)
    {
        if (is_null($secret_access_key)) {
            throw new \InvalidArgumentException('non-nullable secret_access_key cannot be null');
        }
        $this->container['secret_access_key'] = $secret_access_key;

        return $this;
    }

    /**
     * Gets session_token
     *
     * @return string|null
     */
    public function getSessionToken()
    {
        return $this->container['session_token'];
    }

    /**
     * Sets session_token
     *
     * @param string|null $session_token session_token
     *
     * @return self
     */
    public function setSessionToken($session_token)
    {
        if (is_null($session_token)) {
            throw new \InvalidArgumentException('non-nullable session_token cannot be null');
        }
        $this->container['session_token'] = $session_token;

        return $this;
    }

    /**
     * Gets account_id
     *
     * @return string|null
     */
    public function getAccountId()
    {
        return $this->container['account_id'];
    }

    /**
     * Sets account_id
     *
     * @param string|null $account_id account_id
     *
     * @return self
     */
    public function setAccountId($account_id)
    {
        if (is_null($account_id)) {
            throw new \InvalidArgumentException('non-nullable account_id cannot be null');
        }
        $this->container['account_id'] = $account_id;

        return $this;
    }

    /**
     * Gets subscription_id
     *
     * @return string|null
     */
    public function getSubscriptionId()
    {
        return $this->container['subscription_id'];
    }

    /**
     * Sets subscription_id
     *
     * @param string|null $subscription_id subscription_id
     *
     * @return self
     */
    public function setSubscriptionId($subscription_id)
    {
        if (is_null($subscription_id)) {
            throw new \InvalidArgumentException('non-nullable subscription_id cannot be null');
        }
        $this->container['subscription_id'] = $subscription_id;

        return $this;
    }

    /**
     * Gets resource_group
     *
     * @return string|null
     */
    public function getResourceGroup()
    {
        return $this->container['resource_group'];
    }

    /**
     * Sets resource_group
     *
     * @param string|null $resource_group resource_group
     *
     * @return self
     */
    public function setResourceGroup($resource_group)
    {
        if (is_null($resource_group)) {
            throw new \InvalidArgumentException('non-nullable resource_group cannot be null');
        }
        $this->container['resource_group'] = $resource_group;

        return $this;
    }

    /**
     * Gets workspace_name
     *
     * @return string|null
     */
    public function getWorkspaceName()
    {
        return $this->container['workspace_name'];
    }

    /**
     * Sets workspace_name
     *
     * @param string|null $workspace_name workspace_name
     *
     * @return self
     */
    public function setWorkspaceName($workspace_name)
    {
        if (is_null($workspace_name)) {
            throw new \InvalidArgumentException('non-nullable workspace_name cannot be null');
        }
        $this->container['workspace_name'] = $workspace_name;

        return $this;
    }

    /**
     * Gets hugging_face_token
     *
     * @return string|null
     */
    public function getHuggingFaceToken()
    {
        return $this->container['hugging_face_token'];
    }

    /**
     * Sets hugging_face_token
     *
     * @param string|null $hugging_face_token hugging_face_token
     *
     * @return self
     */
    public function setHuggingFaceToken($hugging_face_token)
    {
        if (is_null($hugging_face_token)) {
            throw new \InvalidArgumentException('non-nullable hugging_face_token cannot be null');
        }
        $this->container['hugging_face_token'] = $hugging_face_token;

        return $this;
    }

    /**
     * Gets cohere_api_key
     *
     * @return string|null
     */
    public function getCohereApiKey()
    {
        return $this->container['cohere_api_key'];
    }

    /**
     * Sets cohere_api_key
     *
     * @param string|null $cohere_api_key cohere_api_key
     *
     * @return self
     */
    public function setCohereApiKey($cohere_api_key)
    {
        if (is_null($cohere_api_key)) {
            throw new \InvalidArgumentException('non-nullable cohere_api_key cannot be null');
        }
        $this->container['cohere_api_key'] = $cohere_api_key;

        return $this;
    }

    /**
     * Gets azure_ai_studio_endpoint
     *
     * @return string|null
     */
    public function getAzureAiStudioEndpoint()
    {
        return $this->container['azure_ai_studio_endpoint'];
    }

    /**
     * Sets azure_ai_studio_endpoint
     *
     * @param string|null $azure_ai_studio_endpoint azure_ai_studio_endpoint
     *
     * @return self
     */
    public function setAzureAiStudioEndpoint($azure_ai_studio_endpoint)
    {
        if (is_null($azure_ai_studio_endpoint)) {
            throw new \InvalidArgumentException('non-nullable azure_ai_studio_endpoint cannot be null');
        }
        $this->container['azure_ai_studio_endpoint'] = $azure_ai_studio_endpoint;

        return $this;
    }

    /**
     * Gets mosaicml_api_key
     *
     * @return string|null
     */
    public function getMosaicmlApiKey()
    {
        return $this->container['mosaicml_api_key'];
    }

    /**
     * Sets mosaicml_api_key
     *
     * @param string|null $mosaicml_api_key mosaicml_api_key
     *
     * @return self
     */
    public function setMosaicmlApiKey($mosaicml_api_key)
    {
        if (is_null($mosaicml_api_key)) {
            throw new \InvalidArgumentException('non-nullable mosaicml_api_key cannot be null');
        }
        $this->container['mosaicml_api_key'] = $mosaicml_api_key;

        return $this;
    }

    /**
     * Gets replicate_api_token
     *
     * @return string|null
     */
    public function getReplicateApiToken()
    {
        return $this->container['replicate_api_token'];
    }

    /**
     * Sets replicate_api_token
     *
     * @param string|null $replicate_api_token replicate_api_token
     *
     * @return self
     */
    public function setReplicateApiToken($replicate_api_token)
    {
        if (is_null($replicate_api_token)) {
            throw new \InvalidArgumentException('non-nullable replicate_api_token cannot be null');
        }
        $this->container['replicate_api_token'] = $replicate_api_token;

        return $this;
    }

    /**
     * Gets twitter_bearer_token
     *
     * @return string|null
     */
    public function getTwitterBearerToken()
    {
        return $this->container['twitter_bearer_token'];
    }

    /**
     * Sets twitter_bearer_token
     *
     * @param string|null $twitter_bearer_token twitter_bearer_token
     *
     * @return self
     */
    public function setTwitterBearerToken($twitter_bearer_token)
    {
        if (is_null($twitter_bearer_token)) {
            throw new \InvalidArgumentException('non-nullable twitter_bearer_token cannot be null');
        }
        $this->container['twitter_bearer_token'] = $twitter_bearer_token;

        return $this;
    }

    /**
     * Gets twitter_api_key
     *
     * @return string|null
     */
    public function getTwitterApiKey()
    {
        return $this->container['twitter_api_key'];
    }

    /**
     * Sets twitter_api_key
     *
     * @param string|null $twitter_api_key twitter_api_key
     *
     * @return self
     */
    public function setTwitterApiKey($twitter_api_key)
    {
        if (is_null($twitter_api_key)) {
            throw new \InvalidArgumentException('non-nullable twitter_api_key cannot be null');
        }
        $this->container['twitter_api_key'] = $twitter_api_key;

        return $this;
    }

    /**
     * Gets twitter_api_secret
     *
     * @return string|null
     */
    public function getTwitterApiSecret()
    {
        return $this->container['twitter_api_secret'];
    }

    /**
     * Sets twitter_api_secret
     *
     * @param string|null $twitter_api_secret twitter_api_secret
     *
     * @return self
     */
    public function setTwitterApiSecret($twitter_api_secret)
    {
        if (is_null($twitter_api_secret)) {
            throw new \InvalidArgumentException('non-nullable twitter_api_secret cannot be null');
        }
        $this->container['twitter_api_secret'] = $twitter_api_secret;

        return $this;
    }

    /**
     * Gets reddit_client_id
     *
     * @return string|null
     */
    public function getRedditClientId()
    {
        return $this->container['reddit_client_id'];
    }

    /**
     * Sets reddit_client_id
     *
     * @param string|null $reddit_client_id reddit_client_id
     *
     * @return self
     */
    public function setRedditClientId($reddit_client_id)
    {
        if (is_null($reddit_client_id)) {
            throw new \InvalidArgumentException('non-nullable reddit_client_id cannot be null');
        }
        $this->container['reddit_client_id'] = $reddit_client_id;

        return $this;
    }

    /**
     * Gets reddit_client_secret
     *
     * @return string|null
     */
    public function getRedditClientSecret()
    {
        return $this->container['reddit_client_secret'];
    }

    /**
     * Sets reddit_client_secret
     *
     * @param string|null $reddit_client_secret reddit_client_secret
     *
     * @return self
     */
    public function setRedditClientSecret($reddit_client_secret)
    {
        if (is_null($reddit_client_secret)) {
            throw new \InvalidArgumentException('non-nullable reddit_client_secret cannot be null');
        }
        $this->container['reddit_client_secret'] = $reddit_client_secret;

        return $this;
    }

    /**
     * Gets reddit_user_agent
     *
     * @return string|null
     */
    public function getRedditUserAgent()
    {
        return $this->container['reddit_user_agent'];
    }

    /**
     * Sets reddit_user_agent
     *
     * @param string|null $reddit_user_agent reddit_user_agent
     *
     * @return self
     */
    public function setRedditUserAgent($reddit_user_agent)
    {
        if (is_null($reddit_user_agent)) {
            throw new \InvalidArgumentException('non-nullable reddit_user_agent cannot be null');
        }
        $this->container['reddit_user_agent'] = $reddit_user_agent;

        return $this;
    }

    /**
     * Gets facebook_access_token
     *
     * @return string|null
     */
    public function getFacebookAccessToken()
    {
        return $this->container['facebook_access_token'];
    }

    /**
     * Sets facebook_access_token
     *
     * @param string|null $facebook_access_token facebook_access_token
     *
     * @return self
     */
    public function setFacebookAccessToken($facebook_access_token)
    {
        if (is_null($facebook_access_token)) {
            throw new \InvalidArgumentException('non-nullable facebook_access_token cannot be null');
        }
        $this->container['facebook_access_token'] = $facebook_access_token;

        return $this;
    }

    /**
     * Gets facebook_app_id
     *
     * @return string|null
     */
    public function getFacebookAppId()
    {
        return $this->container['facebook_app_id'];
    }

    /**
     * Sets facebook_app_id
     *
     * @param string|null $facebook_app_id facebook_app_id
     *
     * @return self
     */
    public function setFacebookAppId($facebook_app_id)
    {
        if (is_null($facebook_app_id)) {
            throw new \InvalidArgumentException('non-nullable facebook_app_id cannot be null');
        }
        $this->container['facebook_app_id'] = $facebook_app_id;

        return $this;
    }

    /**
     * Gets facebook_app_secret
     *
     * @return string|null
     */
    public function getFacebookAppSecret()
    {
        return $this->container['facebook_app_secret'];
    }

    /**
     * Sets facebook_app_secret
     *
     * @param string|null $facebook_app_secret facebook_app_secret
     *
     * @return self
     */
    public function setFacebookAppSecret($facebook_app_secret)
    {
        if (is_null($facebook_app_secret)) {
            throw new \InvalidArgumentException('non-nullable facebook_app_secret cannot be null');
        }
        $this->container['facebook_app_secret'] = $facebook_app_secret;

        return $this;
    }

    /**
     * Gets instagram_access_token
     *
     * @return string|null
     */
    public function getInstagramAccessToken()
    {
        return $this->container['instagram_access_token'];
    }

    /**
     * Sets instagram_access_token
     *
     * @param string|null $instagram_access_token instagram_access_token
     *
     * @return self
     */
    public function setInstagramAccessToken($instagram_access_token)
    {
        if (is_null($instagram_access_token)) {
            throw new \InvalidArgumentException('non-nullable instagram_access_token cannot be null');
        }
        $this->container['instagram_access_token'] = $instagram_access_token;

        return $this;
    }

    /**
     * Gets linkedin_access_token
     *
     * @return string|null
     */
    public function getLinkedinAccessToken()
    {
        return $this->container['linkedin_access_token'];
    }

    /**
     * Sets linkedin_access_token
     *
     * @param string|null $linkedin_access_token linkedin_access_token
     *
     * @return self
     */
    public function setLinkedinAccessToken($linkedin_access_token)
    {
        if (is_null($linkedin_access_token)) {
            throw new \InvalidArgumentException('non-nullable linkedin_access_token cannot be null');
        }
        $this->container['linkedin_access_token'] = $linkedin_access_token;

        return $this;
    }

    /**
     * Gets linkedin_client_id
     *
     * @return string|null
     */
    public function getLinkedinClientId()
    {
        return $this->container['linkedin_client_id'];
    }

    /**
     * Sets linkedin_client_id
     *
     * @param string|null $linkedin_client_id linkedin_client_id
     *
     * @return self
     */
    public function setLinkedinClientId($linkedin_client_id)
    {
        if (is_null($linkedin_client_id)) {
            throw new \InvalidArgumentException('non-nullable linkedin_client_id cannot be null');
        }
        $this->container['linkedin_client_id'] = $linkedin_client_id;

        return $this;
    }

    /**
     * Gets linkedin_client_secret
     *
     * @return string|null
     */
    public function getLinkedinClientSecret()
    {
        return $this->container['linkedin_client_secret'];
    }

    /**
     * Sets linkedin_client_secret
     *
     * @param string|null $linkedin_client_secret linkedin_client_secret
     *
     * @return self
     */
    public function setLinkedinClientSecret($linkedin_client_secret)
    {
        if (is_null($linkedin_client_secret)) {
            throw new \InvalidArgumentException('non-nullable linkedin_client_secret cannot be null');
        }
        $this->container['linkedin_client_secret'] = $linkedin_client_secret;

        return $this;
    }

    /**
     * Gets tiktok_client_key
     *
     * @return string|null
     */
    public function getTiktokClientKey()
    {
        return $this->container['tiktok_client_key'];
    }

    /**
     * Sets tiktok_client_key
     *
     * @param string|null $tiktok_client_key tiktok_client_key
     *
     * @return self
     */
    public function setTiktokClientKey($tiktok_client_key)
    {
        if (is_null($tiktok_client_key)) {
            throw new \InvalidArgumentException('non-nullable tiktok_client_key cannot be null');
        }
        $this->container['tiktok_client_key'] = $tiktok_client_key;

        return $this;
    }

    /**
     * Gets tiktok_client_secret
     *
     * @return string|null
     */
    public function getTiktokClientSecret()
    {
        return $this->container['tiktok_client_secret'];
    }

    /**
     * Sets tiktok_client_secret
     *
     * @param string|null $tiktok_client_secret tiktok_client_secret
     *
     * @return self
     */
    public function setTiktokClientSecret($tiktok_client_secret)
    {
        if (is_null($tiktok_client_secret)) {
            throw new \InvalidArgumentException('non-nullable tiktok_client_secret cannot be null');
        }
        $this->container['tiktok_client_secret'] = $tiktok_client_secret;

        return $this;
    }

    /**
     * Gets youtube_api_key
     *
     * @return string|null
     */
    public function getYoutubeApiKey()
    {
        return $this->container['youtube_api_key'];
    }

    /**
     * Sets youtube_api_key
     *
     * @param string|null $youtube_api_key youtube_api_key
     *
     * @return self
     */
    public function setYoutubeApiKey($youtube_api_key)
    {
        if (is_null($youtube_api_key)) {
            throw new \InvalidArgumentException('non-nullable youtube_api_key cannot be null');
        }
        $this->container['youtube_api_key'] = $youtube_api_key;

        return $this;
    }

    /**
     * Gets databricks_workspace_url
     *
     * @return string|null
     */
    public function getDatabricksWorkspaceUrl()
    {
        return $this->container['databricks_workspace_url'];
    }

    /**
     * Sets databricks_workspace_url
     *
     * @param string|null $databricks_workspace_url databricks_workspace_url
     *
     * @return self
     */
    public function setDatabricksWorkspaceUrl($databricks_workspace_url)
    {
        if (is_null($databricks_workspace_url)) {
            throw new \InvalidArgumentException('non-nullable databricks_workspace_url cannot be null');
        }
        $this->container['databricks_workspace_url'] = $databricks_workspace_url;

        return $this;
    }

    /**
     * Gets databricks_access_token
     *
     * @return string|null
     */
    public function getDatabricksAccessToken()
    {
        return $this->container['databricks_access_token'];
    }

    /**
     * Sets databricks_access_token
     *
     * @param string|null $databricks_access_token databricks_access_token
     *
     * @return self
     */
    public function setDatabricksAccessToken($databricks_access_token)
    {
        if (is_null($databricks_access_token)) {
            throw new \InvalidArgumentException('non-nullable databricks_access_token cannot be null');
        }
        $this->container['databricks_access_token'] = $databricks_access_token;

        return $this;
    }

    /**
     * Gets databricks_cluster_id
     *
     * @return string|null
     */
    public function getDatabricksClusterId()
    {
        return $this->container['databricks_cluster_id'];
    }

    /**
     * Sets databricks_cluster_id
     *
     * @param string|null $databricks_cluster_id databricks_cluster_id
     *
     * @return self
     */
    public function setDatabricksClusterId($databricks_cluster_id)
    {
        if (is_null($databricks_cluster_id)) {
            throw new \InvalidArgumentException('non-nullable databricks_cluster_id cannot be null');
        }
        $this->container['databricks_cluster_id'] = $databricks_cluster_id;

        return $this;
    }

    /**
     * Gets oauth_access_token
     *
     * @return string|null
     */
    public function getOauthAccessToken()
    {
        return $this->container['oauth_access_token'];
    }

    /**
     * Sets oauth_access_token
     *
     * @param string|null $oauth_access_token oauth_access_token
     *
     * @return self
     */
    public function setOauthAccessToken($oauth_access_token)
    {
        if (is_null($oauth_access_token)) {
            throw new \InvalidArgumentException('non-nullable oauth_access_token cannot be null');
        }
        $this->container['oauth_access_token'] = $oauth_access_token;

        return $this;
    }

    /**
     * Gets oauth_refresh_token
     *
     * @return string|null
     */
    public function getOauthRefreshToken()
    {
        return $this->container['oauth_refresh_token'];
    }

    /**
     * Sets oauth_refresh_token
     *
     * @param string|null $oauth_refresh_token oauth_refresh_token
     *
     * @return self
     */
    public function setOauthRefreshToken($oauth_refresh_token)
    {
        if (is_null($oauth_refresh_token)) {
            throw new \InvalidArgumentException('non-nullable oauth_refresh_token cannot be null');
        }
        $this->container['oauth_refresh_token'] = $oauth_refresh_token;

        return $this;
    }

    /**
     * Gets oauth_token_expires_at
     *
     * @return \DateTime|null
     */
    public function getOauthTokenExpiresAt()
    {
        return $this->container['oauth_token_expires_at'];
    }

    /**
     * Sets oauth_token_expires_at
     *
     * @param \DateTime|null $oauth_token_expires_at oauth_token_expires_at
     *
     * @return self
     */
    public function setOauthTokenExpiresAt($oauth_token_expires_at)
    {
        if (is_null($oauth_token_expires_at)) {
            throw new \InvalidArgumentException('non-nullable oauth_token_expires_at cannot be null');
        }
        $this->container['oauth_token_expires_at'] = $oauth_token_expires_at;

        return $this;
    }

    /**
     * Gets oauth_token_type
     *
     * @return string|null
     */
    public function getOauthTokenType()
    {
        return $this->container['oauth_token_type'];
    }

    /**
     * Sets oauth_token_type
     *
     * @param string|null $oauth_token_type oauth_token_type
     *
     * @return self
     */
    public function setOauthTokenType($oauth_token_type)
    {
        if (is_null($oauth_token_type)) {
            throw new \InvalidArgumentException('non-nullable oauth_token_type cannot be null');
        }
        $this->container['oauth_token_type'] = $oauth_token_type;

        return $this;
    }

    /**
     * Gets alphavantage_api_key
     *
     * @return string|null
     */
    public function getAlphavantageApiKey()
    {
        return $this->container['alphavantage_api_key'];
    }

    /**
     * Sets alphavantage_api_key
     *
     * @param string|null $alphavantage_api_key alphavantage_api_key
     *
     * @return self
     */
    public function setAlphavantageApiKey($alphavantage_api_key)
    {
        if (is_null($alphavantage_api_key)) {
            throw new \InvalidArgumentException('non-nullable alphavantage_api_key cannot be null');
        }
        $this->container['alphavantage_api_key'] = $alphavantage_api_key;

        return $this;
    }

    /**
     * Gets polygon_api_key
     *
     * @return string|null
     */
    public function getPolygonApiKey()
    {
        return $this->container['polygon_api_key'];
    }

    /**
     * Sets polygon_api_key
     *
     * @param string|null $polygon_api_key polygon_api_key
     *
     * @return self
     */
    public function setPolygonApiKey($polygon_api_key)
    {
        if (is_null($polygon_api_key)) {
            throw new \InvalidArgumentException('non-nullable polygon_api_key cannot be null');
        }
        $this->container['polygon_api_key'] = $polygon_api_key;

        return $this;
    }

    /**
     * Gets twelvedata_api_key
     *
     * @return string|null
     */
    public function getTwelvedataApiKey()
    {
        return $this->container['twelvedata_api_key'];
    }

    /**
     * Sets twelvedata_api_key
     *
     * @param string|null $twelvedata_api_key twelvedata_api_key
     *
     * @return self
     */
    public function setTwelvedataApiKey($twelvedata_api_key)
    {
        if (is_null($twelvedata_api_key)) {
            throw new \InvalidArgumentException('non-nullable twelvedata_api_key cannot be null');
        }
        $this->container['twelvedata_api_key'] = $twelvedata_api_key;

        return $this;
    }

    /**
     * Gets marketstack_access_key
     *
     * @return string|null
     */
    public function getMarketstackAccessKey()
    {
        return $this->container['marketstack_access_key'];
    }

    /**
     * Sets marketstack_access_key
     *
     * @param string|null $marketstack_access_key marketstack_access_key
     *
     * @return self
     */
    public function setMarketstackAccessKey($marketstack_access_key)
    {
        if (is_null($marketstack_access_key)) {
            throw new \InvalidArgumentException('non-nullable marketstack_access_key cannot be null');
        }
        $this->container['marketstack_access_key'] = $marketstack_access_key;

        return $this;
    }

    /**
     * Gets fmp_api_key
     *
     * @return string|null
     */
    public function getFmpApiKey()
    {
        return $this->container['fmp_api_key'];
    }

    /**
     * Sets fmp_api_key
     *
     * @param string|null $fmp_api_key fmp_api_key
     *
     * @return self
     */
    public function setFmpApiKey($fmp_api_key)
    {
        if (is_null($fmp_api_key)) {
            throw new \InvalidArgumentException('non-nullable fmp_api_key cannot be null');
        }
        $this->container['fmp_api_key'] = $fmp_api_key;

        return $this;
    }

    /**
     * Gets iexcloud_token
     *
     * @return string|null
     */
    public function getIexcloudToken()
    {
        return $this->container['iexcloud_token'];
    }

    /**
     * Sets iexcloud_token
     *
     * @param string|null $iexcloud_token iexcloud_token
     *
     * @return self
     */
    public function setIexcloudToken($iexcloud_token)
    {
        if (is_null($iexcloud_token)) {
            throw new \InvalidArgumentException('non-nullable iexcloud_token cannot be null');
        }
        $this->container['iexcloud_token'] = $iexcloud_token;

        return $this;
    }

    /**
     * Gets cbond_api_key
     *
     * @return string|null
     */
    public function getCbondApiKey()
    {
        return $this->container['cbond_api_key'];
    }

    /**
     * Sets cbond_api_key
     *
     * @param string|null $cbond_api_key cbond_api_key
     *
     * @return self
     */
    public function setCbondApiKey($cbond_api_key)
    {
        if (is_null($cbond_api_key)) {
            throw new \InvalidArgumentException('non-nullable cbond_api_key cannot be null');
        }
        $this->container['cbond_api_key'] = $cbond_api_key;

        return $this;
    }

    /**
     * Gets cbond_client_id
     *
     * @return string|null
     */
    public function getCbondClientId()
    {
        return $this->container['cbond_client_id'];
    }

    /**
     * Sets cbond_client_id
     *
     * @param string|null $cbond_client_id cbond_client_id
     *
     * @return self
     */
    public function setCbondClientId($cbond_client_id)
    {
        if (is_null($cbond_client_id)) {
            throw new \InvalidArgumentException('non-nullable cbond_client_id cannot be null');
        }
        $this->container['cbond_client_id'] = $cbond_client_id;

        return $this;
    }

    /**
     * Gets cbond_client_secret
     *
     * @return string|null
     */
    public function getCbondClientSecret()
    {
        return $this->container['cbond_client_secret'];
    }

    /**
     * Sets cbond_client_secret
     *
     * @param string|null $cbond_client_secret cbond_client_secret
     *
     * @return self
     */
    public function setCbondClientSecret($cbond_client_secret)
    {
        if (is_null($cbond_client_secret)) {
            throw new \InvalidArgumentException('non-nullable cbond_client_secret cannot be null');
        }
        $this->container['cbond_client_secret'] = $cbond_client_secret;

        return $this;
    }

    /**
     * Gets google_search_engine_id
     *
     * @return string|null
     */
    public function getGoogleSearchEngineId()
    {
        return $this->container['google_search_engine_id'];
    }

    /**
     * Sets google_search_engine_id
     *
     * @param string|null $google_search_engine_id google_search_engine_id
     *
     * @return self
     */
    public function setGoogleSearchEngineId($google_search_engine_id)
    {
        if (is_null($google_search_engine_id)) {
            throw new \InvalidArgumentException('non-nullable google_search_engine_id cannot be null');
        }
        $this->container['google_search_engine_id'] = $google_search_engine_id;

        return $this;
    }

    /**
     * Gets bing_search_api_key
     *
     * @return string|null
     */
    public function getBingSearchApiKey()
    {
        return $this->container['bing_search_api_key'];
    }

    /**
     * Sets bing_search_api_key
     *
     * @param string|null $bing_search_api_key bing_search_api_key
     *
     * @return self
     */
    public function setBingSearchApiKey($bing_search_api_key)
    {
        if (is_null($bing_search_api_key)) {
            throw new \InvalidArgumentException('non-nullable bing_search_api_key cannot be null');
        }
        $this->container['bing_search_api_key'] = $bing_search_api_key;

        return $this;
    }

    /**
     * Gets enabled
     *
     * @return bool|null
     */
    public function getEnabled()
    {
        return $this->container['enabled'];
    }

    /**
     * Sets enabled
     *
     * @param bool|null $enabled enabled
     *
     * @return self
     */
    public function setEnabled($enabled)
    {
        if (is_null($enabled)) {
            throw new \InvalidArgumentException('non-nullable enabled cannot be null');
        }
        $this->container['enabled'] = $enabled;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


