<?php
/**
 * ExportOptionsDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenAPI
 *
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ExportOptionsDto Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ExportOptionsDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ExportOptionsDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'include_projects' => 'bool',
        'include_agents' => 'bool',
        'include_jobs' => 'bool',
        'include_tasks' => 'bool',
        'include_datasets' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'include_projects' => null,
        'include_agents' => null,
        'include_jobs' => null,
        'include_tasks' => null,
        'include_datasets' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'include_projects' => false,
        'include_agents' => false,
        'include_jobs' => false,
        'include_tasks' => false,
        'include_datasets' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'include_projects' => 'includeProjects',
        'include_agents' => 'includeAgents',
        'include_jobs' => 'includeJobs',
        'include_tasks' => 'includeTasks',
        'include_datasets' => 'includeDatasets'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'include_projects' => 'setIncludeProjects',
        'include_agents' => 'setIncludeAgents',
        'include_jobs' => 'setIncludeJobs',
        'include_tasks' => 'setIncludeTasks',
        'include_datasets' => 'setIncludeDatasets'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'include_projects' => 'getIncludeProjects',
        'include_agents' => 'getIncludeAgents',
        'include_jobs' => 'getIncludeJobs',
        'include_tasks' => 'getIncludeTasks',
        'include_datasets' => 'getIncludeDatasets'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('include_projects', $data ?? [], null);
        $this->setIfExists('include_agents', $data ?? [], null);
        $this->setIfExists('include_jobs', $data ?? [], null);
        $this->setIfExists('include_tasks', $data ?? [], null);
        $this->setIfExists('include_datasets', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets include_projects
     *
     * @return bool|null
     */
    public function getIncludeProjects()
    {
        return $this->container['include_projects'];
    }

    /**
     * Sets include_projects
     *
     * @param bool|null $include_projects include_projects
     *
     * @return self
     */
    public function setIncludeProjects($include_projects)
    {
        if (is_null($include_projects)) {
            throw new \InvalidArgumentException('non-nullable include_projects cannot be null');
        }
        $this->container['include_projects'] = $include_projects;

        return $this;
    }

    /**
     * Gets include_agents
     *
     * @return bool|null
     */
    public function getIncludeAgents()
    {
        return $this->container['include_agents'];
    }

    /**
     * Sets include_agents
     *
     * @param bool|null $include_agents include_agents
     *
     * @return self
     */
    public function setIncludeAgents($include_agents)
    {
        if (is_null($include_agents)) {
            throw new \InvalidArgumentException('non-nullable include_agents cannot be null');
        }
        $this->container['include_agents'] = $include_agents;

        return $this;
    }

    /**
     * Gets include_jobs
     *
     * @return bool|null
     */
    public function getIncludeJobs()
    {
        return $this->container['include_jobs'];
    }

    /**
     * Sets include_jobs
     *
     * @param bool|null $include_jobs include_jobs
     *
     * @return self
     */
    public function setIncludeJobs($include_jobs)
    {
        if (is_null($include_jobs)) {
            throw new \InvalidArgumentException('non-nullable include_jobs cannot be null');
        }
        $this->container['include_jobs'] = $include_jobs;

        return $this;
    }

    /**
     * Gets include_tasks
     *
     * @return bool|null
     */
    public function getIncludeTasks()
    {
        return $this->container['include_tasks'];
    }

    /**
     * Sets include_tasks
     *
     * @param bool|null $include_tasks include_tasks
     *
     * @return self
     */
    public function setIncludeTasks($include_tasks)
    {
        if (is_null($include_tasks)) {
            throw new \InvalidArgumentException('non-nullable include_tasks cannot be null');
        }
        $this->container['include_tasks'] = $include_tasks;

        return $this;
    }

    /**
     * Gets include_datasets
     *
     * @return bool|null
     */
    public function getIncludeDatasets()
    {
        return $this->container['include_datasets'];
    }

    /**
     * Sets include_datasets
     *
     * @param bool|null $include_datasets include_datasets
     *
     * @return self
     */
    public function setIncludeDatasets($include_datasets)
    {
        if (is_null($include_datasets)) {
            throw new \InvalidArgumentException('non-nullable include_datasets cannot be null');
        }
        $this->container['include_datasets'] = $include_datasets;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


