<?php
/**
 * JobCompletionWebhookRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenAPI
 *
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * JobCompletionWebhookRequest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class JobCompletionWebhookRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'JobCompletionWebhookRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'job_id' => 'string',
        'execution_id' => 'string',
        'spark_application_name' => 'string',
        'status' => 'string',
        'output_dataset_path' => 'string',
        'output_dataset_format' => 'string',
        'output_dataset_schema' => 'string',
        'duration_seconds' => 'int',
        'records_processed' => 'int',
        'records_output' => 'int',
        'output_file_size_bytes' => 'int',
        'partitions_count' => 'int',
        'driver_memory_used_bytes' => 'int',
        'executor_memory_used_bytes' => 'int',
        'executor_count' => 'int',
        'total_cpu_time_seconds' => 'int',
        'error_count' => 'int',
        'warning_count' => 'int',
        'error_message' => 'string',
        'additional_metrics' => 'array<string,object>',
        'started_at' => 'string',
        'completed_at' => 'string',
        'spark_ui_url' => 'string',
        'metrics' => 'array<string,object>'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'job_id' => null,
        'execution_id' => null,
        'spark_application_name' => null,
        'status' => null,
        'output_dataset_path' => null,
        'output_dataset_format' => null,
        'output_dataset_schema' => null,
        'duration_seconds' => 'int64',
        'records_processed' => 'int64',
        'records_output' => 'int64',
        'output_file_size_bytes' => 'int64',
        'partitions_count' => 'int32',
        'driver_memory_used_bytes' => 'int64',
        'executor_memory_used_bytes' => 'int64',
        'executor_count' => 'int32',
        'total_cpu_time_seconds' => 'int64',
        'error_count' => 'int32',
        'warning_count' => 'int32',
        'error_message' => null,
        'additional_metrics' => null,
        'started_at' => null,
        'completed_at' => null,
        'spark_ui_url' => null,
        'metrics' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'job_id' => false,
        'execution_id' => false,
        'spark_application_name' => false,
        'status' => false,
        'output_dataset_path' => false,
        'output_dataset_format' => false,
        'output_dataset_schema' => false,
        'duration_seconds' => false,
        'records_processed' => false,
        'records_output' => false,
        'output_file_size_bytes' => false,
        'partitions_count' => false,
        'driver_memory_used_bytes' => false,
        'executor_memory_used_bytes' => false,
        'executor_count' => false,
        'total_cpu_time_seconds' => false,
        'error_count' => false,
        'warning_count' => false,
        'error_message' => false,
        'additional_metrics' => false,
        'started_at' => false,
        'completed_at' => false,
        'spark_ui_url' => false,
        'metrics' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'job_id' => 'jobId',
        'execution_id' => 'executionId',
        'spark_application_name' => 'sparkApplicationName',
        'status' => 'status',
        'output_dataset_path' => 'outputDatasetPath',
        'output_dataset_format' => 'outputDatasetFormat',
        'output_dataset_schema' => 'outputDatasetSchema',
        'duration_seconds' => 'durationSeconds',
        'records_processed' => 'recordsProcessed',
        'records_output' => 'recordsOutput',
        'output_file_size_bytes' => 'outputFileSizeBytes',
        'partitions_count' => 'partitionsCount',
        'driver_memory_used_bytes' => 'driverMemoryUsedBytes',
        'executor_memory_used_bytes' => 'executorMemoryUsedBytes',
        'executor_count' => 'executorCount',
        'total_cpu_time_seconds' => 'totalCpuTimeSeconds',
        'error_count' => 'errorCount',
        'warning_count' => 'warningCount',
        'error_message' => 'errorMessage',
        'additional_metrics' => 'additionalMetrics',
        'started_at' => 'startedAt',
        'completed_at' => 'completedAt',
        'spark_ui_url' => 'sparkUiUrl',
        'metrics' => 'metrics'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'job_id' => 'setJobId',
        'execution_id' => 'setExecutionId',
        'spark_application_name' => 'setSparkApplicationName',
        'status' => 'setStatus',
        'output_dataset_path' => 'setOutputDatasetPath',
        'output_dataset_format' => 'setOutputDatasetFormat',
        'output_dataset_schema' => 'setOutputDatasetSchema',
        'duration_seconds' => 'setDurationSeconds',
        'records_processed' => 'setRecordsProcessed',
        'records_output' => 'setRecordsOutput',
        'output_file_size_bytes' => 'setOutputFileSizeBytes',
        'partitions_count' => 'setPartitionsCount',
        'driver_memory_used_bytes' => 'setDriverMemoryUsedBytes',
        'executor_memory_used_bytes' => 'setExecutorMemoryUsedBytes',
        'executor_count' => 'setExecutorCount',
        'total_cpu_time_seconds' => 'setTotalCpuTimeSeconds',
        'error_count' => 'setErrorCount',
        'warning_count' => 'setWarningCount',
        'error_message' => 'setErrorMessage',
        'additional_metrics' => 'setAdditionalMetrics',
        'started_at' => 'setStartedAt',
        'completed_at' => 'setCompletedAt',
        'spark_ui_url' => 'setSparkUiUrl',
        'metrics' => 'setMetrics'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'job_id' => 'getJobId',
        'execution_id' => 'getExecutionId',
        'spark_application_name' => 'getSparkApplicationName',
        'status' => 'getStatus',
        'output_dataset_path' => 'getOutputDatasetPath',
        'output_dataset_format' => 'getOutputDatasetFormat',
        'output_dataset_schema' => 'getOutputDatasetSchema',
        'duration_seconds' => 'getDurationSeconds',
        'records_processed' => 'getRecordsProcessed',
        'records_output' => 'getRecordsOutput',
        'output_file_size_bytes' => 'getOutputFileSizeBytes',
        'partitions_count' => 'getPartitionsCount',
        'driver_memory_used_bytes' => 'getDriverMemoryUsedBytes',
        'executor_memory_used_bytes' => 'getExecutorMemoryUsedBytes',
        'executor_count' => 'getExecutorCount',
        'total_cpu_time_seconds' => 'getTotalCpuTimeSeconds',
        'error_count' => 'getErrorCount',
        'warning_count' => 'getWarningCount',
        'error_message' => 'getErrorMessage',
        'additional_metrics' => 'getAdditionalMetrics',
        'started_at' => 'getStartedAt',
        'completed_at' => 'getCompletedAt',
        'spark_ui_url' => 'getSparkUiUrl',
        'metrics' => 'getMetrics'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('job_id', $data ?? [], null);
        $this->setIfExists('execution_id', $data ?? [], null);
        $this->setIfExists('spark_application_name', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('output_dataset_path', $data ?? [], null);
        $this->setIfExists('output_dataset_format', $data ?? [], null);
        $this->setIfExists('output_dataset_schema', $data ?? [], null);
        $this->setIfExists('duration_seconds', $data ?? [], null);
        $this->setIfExists('records_processed', $data ?? [], null);
        $this->setIfExists('records_output', $data ?? [], null);
        $this->setIfExists('output_file_size_bytes', $data ?? [], null);
        $this->setIfExists('partitions_count', $data ?? [], null);
        $this->setIfExists('driver_memory_used_bytes', $data ?? [], null);
        $this->setIfExists('executor_memory_used_bytes', $data ?? [], null);
        $this->setIfExists('executor_count', $data ?? [], null);
        $this->setIfExists('total_cpu_time_seconds', $data ?? [], null);
        $this->setIfExists('error_count', $data ?? [], null);
        $this->setIfExists('warning_count', $data ?? [], null);
        $this->setIfExists('error_message', $data ?? [], null);
        $this->setIfExists('additional_metrics', $data ?? [], null);
        $this->setIfExists('started_at', $data ?? [], null);
        $this->setIfExists('completed_at', $data ?? [], null);
        $this->setIfExists('spark_ui_url', $data ?? [], null);
        $this->setIfExists('metrics', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets job_id
     *
     * @return string|null
     */
    public function getJobId()
    {
        return $this->container['job_id'];
    }

    /**
     * Sets job_id
     *
     * @param string|null $job_id job_id
     *
     * @return self
     */
    public function setJobId($job_id)
    {
        if (is_null($job_id)) {
            throw new \InvalidArgumentException('non-nullable job_id cannot be null');
        }
        $this->container['job_id'] = $job_id;

        return $this;
    }

    /**
     * Gets execution_id
     *
     * @return string|null
     */
    public function getExecutionId()
    {
        return $this->container['execution_id'];
    }

    /**
     * Sets execution_id
     *
     * @param string|null $execution_id execution_id
     *
     * @return self
     */
    public function setExecutionId($execution_id)
    {
        if (is_null($execution_id)) {
            throw new \InvalidArgumentException('non-nullable execution_id cannot be null');
        }
        $this->container['execution_id'] = $execution_id;

        return $this;
    }

    /**
     * Gets spark_application_name
     *
     * @return string|null
     */
    public function getSparkApplicationName()
    {
        return $this->container['spark_application_name'];
    }

    /**
     * Sets spark_application_name
     *
     * @param string|null $spark_application_name spark_application_name
     *
     * @return self
     */
    public function setSparkApplicationName($spark_application_name)
    {
        if (is_null($spark_application_name)) {
            throw new \InvalidArgumentException('non-nullable spark_application_name cannot be null');
        }
        $this->container['spark_application_name'] = $spark_application_name;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets output_dataset_path
     *
     * @return string|null
     */
    public function getOutputDatasetPath()
    {
        return $this->container['output_dataset_path'];
    }

    /**
     * Sets output_dataset_path
     *
     * @param string|null $output_dataset_path output_dataset_path
     *
     * @return self
     */
    public function setOutputDatasetPath($output_dataset_path)
    {
        if (is_null($output_dataset_path)) {
            throw new \InvalidArgumentException('non-nullable output_dataset_path cannot be null');
        }
        $this->container['output_dataset_path'] = $output_dataset_path;

        return $this;
    }

    /**
     * Gets output_dataset_format
     *
     * @return string|null
     */
    public function getOutputDatasetFormat()
    {
        return $this->container['output_dataset_format'];
    }

    /**
     * Sets output_dataset_format
     *
     * @param string|null $output_dataset_format output_dataset_format
     *
     * @return self
     */
    public function setOutputDatasetFormat($output_dataset_format)
    {
        if (is_null($output_dataset_format)) {
            throw new \InvalidArgumentException('non-nullable output_dataset_format cannot be null');
        }
        $this->container['output_dataset_format'] = $output_dataset_format;

        return $this;
    }

    /**
     * Gets output_dataset_schema
     *
     * @return string|null
     */
    public function getOutputDatasetSchema()
    {
        return $this->container['output_dataset_schema'];
    }

    /**
     * Sets output_dataset_schema
     *
     * @param string|null $output_dataset_schema output_dataset_schema
     *
     * @return self
     */
    public function setOutputDatasetSchema($output_dataset_schema)
    {
        if (is_null($output_dataset_schema)) {
            throw new \InvalidArgumentException('non-nullable output_dataset_schema cannot be null');
        }
        $this->container['output_dataset_schema'] = $output_dataset_schema;

        return $this;
    }

    /**
     * Gets duration_seconds
     *
     * @return int|null
     */
    public function getDurationSeconds()
    {
        return $this->container['duration_seconds'];
    }

    /**
     * Sets duration_seconds
     *
     * @param int|null $duration_seconds duration_seconds
     *
     * @return self
     */
    public function setDurationSeconds($duration_seconds)
    {
        if (is_null($duration_seconds)) {
            throw new \InvalidArgumentException('non-nullable duration_seconds cannot be null');
        }
        $this->container['duration_seconds'] = $duration_seconds;

        return $this;
    }

    /**
     * Gets records_processed
     *
     * @return int|null
     */
    public function getRecordsProcessed()
    {
        return $this->container['records_processed'];
    }

    /**
     * Sets records_processed
     *
     * @param int|null $records_processed records_processed
     *
     * @return self
     */
    public function setRecordsProcessed($records_processed)
    {
        if (is_null($records_processed)) {
            throw new \InvalidArgumentException('non-nullable records_processed cannot be null');
        }
        $this->container['records_processed'] = $records_processed;

        return $this;
    }

    /**
     * Gets records_output
     *
     * @return int|null
     */
    public function getRecordsOutput()
    {
        return $this->container['records_output'];
    }

    /**
     * Sets records_output
     *
     * @param int|null $records_output records_output
     *
     * @return self
     */
    public function setRecordsOutput($records_output)
    {
        if (is_null($records_output)) {
            throw new \InvalidArgumentException('non-nullable records_output cannot be null');
        }
        $this->container['records_output'] = $records_output;

        return $this;
    }

    /**
     * Gets output_file_size_bytes
     *
     * @return int|null
     */
    public function getOutputFileSizeBytes()
    {
        return $this->container['output_file_size_bytes'];
    }

    /**
     * Sets output_file_size_bytes
     *
     * @param int|null $output_file_size_bytes output_file_size_bytes
     *
     * @return self
     */
    public function setOutputFileSizeBytes($output_file_size_bytes)
    {
        if (is_null($output_file_size_bytes)) {
            throw new \InvalidArgumentException('non-nullable output_file_size_bytes cannot be null');
        }
        $this->container['output_file_size_bytes'] = $output_file_size_bytes;

        return $this;
    }

    /**
     * Gets partitions_count
     *
     * @return int|null
     */
    public function getPartitionsCount()
    {
        return $this->container['partitions_count'];
    }

    /**
     * Sets partitions_count
     *
     * @param int|null $partitions_count partitions_count
     *
     * @return self
     */
    public function setPartitionsCount($partitions_count)
    {
        if (is_null($partitions_count)) {
            throw new \InvalidArgumentException('non-nullable partitions_count cannot be null');
        }
        $this->container['partitions_count'] = $partitions_count;

        return $this;
    }

    /**
     * Gets driver_memory_used_bytes
     *
     * @return int|null
     */
    public function getDriverMemoryUsedBytes()
    {
        return $this->container['driver_memory_used_bytes'];
    }

    /**
     * Sets driver_memory_used_bytes
     *
     * @param int|null $driver_memory_used_bytes driver_memory_used_bytes
     *
     * @return self
     */
    public function setDriverMemoryUsedBytes($driver_memory_used_bytes)
    {
        if (is_null($driver_memory_used_bytes)) {
            throw new \InvalidArgumentException('non-nullable driver_memory_used_bytes cannot be null');
        }
        $this->container['driver_memory_used_bytes'] = $driver_memory_used_bytes;

        return $this;
    }

    /**
     * Gets executor_memory_used_bytes
     *
     * @return int|null
     */
    public function getExecutorMemoryUsedBytes()
    {
        return $this->container['executor_memory_used_bytes'];
    }

    /**
     * Sets executor_memory_used_bytes
     *
     * @param int|null $executor_memory_used_bytes executor_memory_used_bytes
     *
     * @return self
     */
    public function setExecutorMemoryUsedBytes($executor_memory_used_bytes)
    {
        if (is_null($executor_memory_used_bytes)) {
            throw new \InvalidArgumentException('non-nullable executor_memory_used_bytes cannot be null');
        }
        $this->container['executor_memory_used_bytes'] = $executor_memory_used_bytes;

        return $this;
    }

    /**
     * Gets executor_count
     *
     * @return int|null
     */
    public function getExecutorCount()
    {
        return $this->container['executor_count'];
    }

    /**
     * Sets executor_count
     *
     * @param int|null $executor_count executor_count
     *
     * @return self
     */
    public function setExecutorCount($executor_count)
    {
        if (is_null($executor_count)) {
            throw new \InvalidArgumentException('non-nullable executor_count cannot be null');
        }
        $this->container['executor_count'] = $executor_count;

        return $this;
    }

    /**
     * Gets total_cpu_time_seconds
     *
     * @return int|null
     */
    public function getTotalCpuTimeSeconds()
    {
        return $this->container['total_cpu_time_seconds'];
    }

    /**
     * Sets total_cpu_time_seconds
     *
     * @param int|null $total_cpu_time_seconds total_cpu_time_seconds
     *
     * @return self
     */
    public function setTotalCpuTimeSeconds($total_cpu_time_seconds)
    {
        if (is_null($total_cpu_time_seconds)) {
            throw new \InvalidArgumentException('non-nullable total_cpu_time_seconds cannot be null');
        }
        $this->container['total_cpu_time_seconds'] = $total_cpu_time_seconds;

        return $this;
    }

    /**
     * Gets error_count
     *
     * @return int|null
     */
    public function getErrorCount()
    {
        return $this->container['error_count'];
    }

    /**
     * Sets error_count
     *
     * @param int|null $error_count error_count
     *
     * @return self
     */
    public function setErrorCount($error_count)
    {
        if (is_null($error_count)) {
            throw new \InvalidArgumentException('non-nullable error_count cannot be null');
        }
        $this->container['error_count'] = $error_count;

        return $this;
    }

    /**
     * Gets warning_count
     *
     * @return int|null
     */
    public function getWarningCount()
    {
        return $this->container['warning_count'];
    }

    /**
     * Sets warning_count
     *
     * @param int|null $warning_count warning_count
     *
     * @return self
     */
    public function setWarningCount($warning_count)
    {
        if (is_null($warning_count)) {
            throw new \InvalidArgumentException('non-nullable warning_count cannot be null');
        }
        $this->container['warning_count'] = $warning_count;

        return $this;
    }

    /**
     * Gets error_message
     *
     * @return string|null
     */
    public function getErrorMessage()
    {
        return $this->container['error_message'];
    }

    /**
     * Sets error_message
     *
     * @param string|null $error_message error_message
     *
     * @return self
     */
    public function setErrorMessage($error_message)
    {
        if (is_null($error_message)) {
            throw new \InvalidArgumentException('non-nullable error_message cannot be null');
        }
        $this->container['error_message'] = $error_message;

        return $this;
    }

    /**
     * Gets additional_metrics
     *
     * @return array<string,object>|null
     */
    public function getAdditionalMetrics()
    {
        return $this->container['additional_metrics'];
    }

    /**
     * Sets additional_metrics
     *
     * @param array<string,object>|null $additional_metrics additional_metrics
     *
     * @return self
     */
    public function setAdditionalMetrics($additional_metrics)
    {
        if (is_null($additional_metrics)) {
            throw new \InvalidArgumentException('non-nullable additional_metrics cannot be null');
        }
        $this->container['additional_metrics'] = $additional_metrics;

        return $this;
    }

    /**
     * Gets started_at
     *
     * @return string|null
     */
    public function getStartedAt()
    {
        return $this->container['started_at'];
    }

    /**
     * Sets started_at
     *
     * @param string|null $started_at started_at
     *
     * @return self
     */
    public function setStartedAt($started_at)
    {
        if (is_null($started_at)) {
            throw new \InvalidArgumentException('non-nullable started_at cannot be null');
        }
        $this->container['started_at'] = $started_at;

        return $this;
    }

    /**
     * Gets completed_at
     *
     * @return string|null
     */
    public function getCompletedAt()
    {
        return $this->container['completed_at'];
    }

    /**
     * Sets completed_at
     *
     * @param string|null $completed_at completed_at
     *
     * @return self
     */
    public function setCompletedAt($completed_at)
    {
        if (is_null($completed_at)) {
            throw new \InvalidArgumentException('non-nullable completed_at cannot be null');
        }
        $this->container['completed_at'] = $completed_at;

        return $this;
    }

    /**
     * Gets spark_ui_url
     *
     * @return string|null
     */
    public function getSparkUiUrl()
    {
        return $this->container['spark_ui_url'];
    }

    /**
     * Sets spark_ui_url
     *
     * @param string|null $spark_ui_url spark_ui_url
     *
     * @return self
     */
    public function setSparkUiUrl($spark_ui_url)
    {
        if (is_null($spark_ui_url)) {
            throw new \InvalidArgumentException('non-nullable spark_ui_url cannot be null');
        }
        $this->container['spark_ui_url'] = $spark_ui_url;

        return $this;
    }

    /**
     * Gets metrics
     *
     * @return array<string,object>|null
     */
    public function getMetrics()
    {
        return $this->container['metrics'];
    }

    /**
     * Sets metrics
     *
     * @param array<string,object>|null $metrics metrics
     *
     * @return self
     */
    public function setMetrics($metrics)
    {
        if (is_null($metrics)) {
            throw new \InvalidArgumentException('non-nullable metrics cannot be null');
        }
        $this->container['metrics'] = $metrics;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


