<?php
/**
 * JobDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenAPI
 *
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * JobDto Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class JobDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'JobDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'name' => 'string',
        'description' => 'string',
        'project_id' => 'string',
        'agent_id' => 'string',
        'input_dataset_id' => 'string',
        'cloud_credential_id' => 'string',
        'cloud_credential_ids' => 'string[]',
        'execution_status' => 'string',
        'scheduled_time' => '\DateTime',
        'enabled' => 'bool',
        'task_ids' => 'string[]',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'job_type' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'name' => null,
        'description' => null,
        'project_id' => null,
        'agent_id' => null,
        'input_dataset_id' => null,
        'cloud_credential_id' => null,
        'cloud_credential_ids' => null,
        'execution_status' => null,
        'scheduled_time' => 'date-time',
        'enabled' => null,
        'task_ids' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'job_type' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'name' => false,
        'description' => false,
        'project_id' => false,
        'agent_id' => false,
        'input_dataset_id' => false,
        'cloud_credential_id' => false,
        'cloud_credential_ids' => false,
        'execution_status' => false,
        'scheduled_time' => false,
        'enabled' => false,
        'task_ids' => false,
        'created_at' => false,
        'updated_at' => false,
        'job_type' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'description' => 'description',
        'project_id' => 'projectId',
        'agent_id' => 'agentId',
        'input_dataset_id' => 'inputDatasetId',
        'cloud_credential_id' => 'cloudCredentialId',
        'cloud_credential_ids' => 'cloudCredentialIds',
        'execution_status' => 'executionStatus',
        'scheduled_time' => 'scheduledTime',
        'enabled' => 'enabled',
        'task_ids' => 'taskIds',
        'created_at' => 'createdAt',
        'updated_at' => 'updatedAt',
        'job_type' => 'jobType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'description' => 'setDescription',
        'project_id' => 'setProjectId',
        'agent_id' => 'setAgentId',
        'input_dataset_id' => 'setInputDatasetId',
        'cloud_credential_id' => 'setCloudCredentialId',
        'cloud_credential_ids' => 'setCloudCredentialIds',
        'execution_status' => 'setExecutionStatus',
        'scheduled_time' => 'setScheduledTime',
        'enabled' => 'setEnabled',
        'task_ids' => 'setTaskIds',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'job_type' => 'setJobType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'description' => 'getDescription',
        'project_id' => 'getProjectId',
        'agent_id' => 'getAgentId',
        'input_dataset_id' => 'getInputDatasetId',
        'cloud_credential_id' => 'getCloudCredentialId',
        'cloud_credential_ids' => 'getCloudCredentialIds',
        'execution_status' => 'getExecutionStatus',
        'scheduled_time' => 'getScheduledTime',
        'enabled' => 'getEnabled',
        'task_ids' => 'getTaskIds',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'job_type' => 'getJobType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const EXECUTION_STATUS_CREATED = 'CREATED';
    public const EXECUTION_STATUS_PENDING = 'PENDING';
    public const EXECUTION_STATUS_RUNNING = 'RUNNING';
    public const EXECUTION_STATUS_COMPLETED = 'COMPLETED';
    public const EXECUTION_STATUS_FAILED = 'FAILED';
    public const JOB_TYPE_BATCH = 'BATCH';
    public const JOB_TYPE_STREAMING = 'STREAMING';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getExecutionStatusAllowableValues()
    {
        return [
            self::EXECUTION_STATUS_CREATED,
            self::EXECUTION_STATUS_PENDING,
            self::EXECUTION_STATUS_RUNNING,
            self::EXECUTION_STATUS_COMPLETED,
            self::EXECUTION_STATUS_FAILED,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getJobTypeAllowableValues()
    {
        return [
            self::JOB_TYPE_BATCH,
            self::JOB_TYPE_STREAMING,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('project_id', $data ?? [], null);
        $this->setIfExists('agent_id', $data ?? [], null);
        $this->setIfExists('input_dataset_id', $data ?? [], null);
        $this->setIfExists('cloud_credential_id', $data ?? [], null);
        $this->setIfExists('cloud_credential_ids', $data ?? [], null);
        $this->setIfExists('execution_status', $data ?? [], null);
        $this->setIfExists('scheduled_time', $data ?? [], null);
        $this->setIfExists('enabled', $data ?? [], null);
        $this->setIfExists('task_ids', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
        $this->setIfExists('job_type', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getExecutionStatusAllowableValues();
        if (!is_null($this->container['execution_status']) && !in_array($this->container['execution_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'execution_status', must be one of '%s'",
                $this->container['execution_status'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getJobTypeAllowableValues();
        if (!is_null($this->container['job_type']) && !in_array($this->container['job_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'job_type', must be one of '%s'",
                $this->container['job_type'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets project_id
     *
     * @return string|null
     */
    public function getProjectId()
    {
        return $this->container['project_id'];
    }

    /**
     * Sets project_id
     *
     * @param string|null $project_id project_id
     *
     * @return self
     */
    public function setProjectId($project_id)
    {
        if (is_null($project_id)) {
            throw new \InvalidArgumentException('non-nullable project_id cannot be null');
        }
        $this->container['project_id'] = $project_id;

        return $this;
    }

    /**
     * Gets agent_id
     *
     * @return string|null
     */
    public function getAgentId()
    {
        return $this->container['agent_id'];
    }

    /**
     * Sets agent_id
     *
     * @param string|null $agent_id agent_id
     *
     * @return self
     */
    public function setAgentId($agent_id)
    {
        if (is_null($agent_id)) {
            throw new \InvalidArgumentException('non-nullable agent_id cannot be null');
        }
        $this->container['agent_id'] = $agent_id;

        return $this;
    }

    /**
     * Gets input_dataset_id
     *
     * @return string|null
     */
    public function getInputDatasetId()
    {
        return $this->container['input_dataset_id'];
    }

    /**
     * Sets input_dataset_id
     *
     * @param string|null $input_dataset_id input_dataset_id
     *
     * @return self
     */
    public function setInputDatasetId($input_dataset_id)
    {
        if (is_null($input_dataset_id)) {
            throw new \InvalidArgumentException('non-nullable input_dataset_id cannot be null');
        }
        $this->container['input_dataset_id'] = $input_dataset_id;

        return $this;
    }

    /**
     * Gets cloud_credential_id
     *
     * @return string|null
     */
    public function getCloudCredentialId()
    {
        return $this->container['cloud_credential_id'];
    }

    /**
     * Sets cloud_credential_id
     *
     * @param string|null $cloud_credential_id cloud_credential_id
     *
     * @return self
     */
    public function setCloudCredentialId($cloud_credential_id)
    {
        if (is_null($cloud_credential_id)) {
            throw new \InvalidArgumentException('non-nullable cloud_credential_id cannot be null');
        }
        $this->container['cloud_credential_id'] = $cloud_credential_id;

        return $this;
    }

    /**
     * Gets cloud_credential_ids
     *
     * @return string[]|null
     */
    public function getCloudCredentialIds()
    {
        return $this->container['cloud_credential_ids'];
    }

    /**
     * Sets cloud_credential_ids
     *
     * @param string[]|null $cloud_credential_ids cloud_credential_ids
     *
     * @return self
     */
    public function setCloudCredentialIds($cloud_credential_ids)
    {
        if (is_null($cloud_credential_ids)) {
            throw new \InvalidArgumentException('non-nullable cloud_credential_ids cannot be null');
        }
        $this->container['cloud_credential_ids'] = $cloud_credential_ids;

        return $this;
    }

    /**
     * Gets execution_status
     *
     * @return string|null
     */
    public function getExecutionStatus()
    {
        return $this->container['execution_status'];
    }

    /**
     * Sets execution_status
     *
     * @param string|null $execution_status execution_status
     *
     * @return self
     */
    public function setExecutionStatus($execution_status)
    {
        if (is_null($execution_status)) {
            throw new \InvalidArgumentException('non-nullable execution_status cannot be null');
        }
        $allowedValues = $this->getExecutionStatusAllowableValues();
        if (!in_array($execution_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'execution_status', must be one of '%s'",
                    $execution_status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['execution_status'] = $execution_status;

        return $this;
    }

    /**
     * Gets scheduled_time
     *
     * @return \DateTime|null
     */
    public function getScheduledTime()
    {
        return $this->container['scheduled_time'];
    }

    /**
     * Sets scheduled_time
     *
     * @param \DateTime|null $scheduled_time scheduled_time
     *
     * @return self
     */
    public function setScheduledTime($scheduled_time)
    {
        if (is_null($scheduled_time)) {
            throw new \InvalidArgumentException('non-nullable scheduled_time cannot be null');
        }
        $this->container['scheduled_time'] = $scheduled_time;

        return $this;
    }

    /**
     * Gets enabled
     *
     * @return bool|null
     */
    public function getEnabled()
    {
        return $this->container['enabled'];
    }

    /**
     * Sets enabled
     *
     * @param bool|null $enabled enabled
     *
     * @return self
     */
    public function setEnabled($enabled)
    {
        if (is_null($enabled)) {
            throw new \InvalidArgumentException('non-nullable enabled cannot be null');
        }
        $this->container['enabled'] = $enabled;

        return $this;
    }

    /**
     * Gets task_ids
     *
     * @return string[]|null
     */
    public function getTaskIds()
    {
        return $this->container['task_ids'];
    }

    /**
     * Sets task_ids
     *
     * @param string[]|null $task_ids task_ids
     *
     * @return self
     */
    public function setTaskIds($task_ids)
    {
        if (is_null($task_ids)) {
            throw new \InvalidArgumentException('non-nullable task_ids cannot be null');
        }
        $this->container['task_ids'] = $task_ids;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime|null $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime|null $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets job_type
     *
     * @return string|null
     */
    public function getJobType()
    {
        return $this->container['job_type'];
    }

    /**
     * Sets job_type
     *
     * @param string|null $job_type job_type
     *
     * @return self
     */
    public function setJobType($job_type)
    {
        if (is_null($job_type)) {
            throw new \InvalidArgumentException('non-nullable job_type cannot be null');
        }
        $allowedValues = $this->getJobTypeAllowableValues();
        if (!in_array($job_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'job_type', must be one of '%s'",
                    $job_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['job_type'] = $job_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


